import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // Power Distribution
  {
    id: "c0a80101-003b-4000-8000-000000000059",
    deviceType: "power-distribution",
    label: "Power Strip",
    searchTerms: ["power strip", "power bar", "outlet strip", "surge protector"],
    ports: [
      port("AC In", "power", "input", "edison"),
      port("Out 1", "power", "output", "edison"),
      port("Out 2", "power", "output", "edison"),
      port("Out 3", "power", "output", "edison"),
      port("Out 4", "power", "output", "edison"),
      port("Out 5", "power", "output", "edison"),
      port("Out 6", "power", "output", "edison"),
    ],
  },
  {
    id: "c0a80101-003c-4000-8000-000000000060",
    deviceType: "power-distribution",
    label: "Rack PDU",
    searchTerms: ["pdu", "power distribution", "rack power"],
    ports: [
      port("AC In", "power", "input", "edison"),
      port("Out 1", "power", "output"),
      port("Out 2", "power", "output"),
      port("Out 3", "power", "output"),
      port("Out 4", "power", "output"),
      port("Out 5", "power", "output"),
      port("Out 6", "power", "output"),
      port("Out 7", "power", "output"),
      port("Out 8", "power", "output"),
      port("Out 9", "power", "output"),
      port("Out 10", "power", "output"),
      port("Out 11", "power", "output"),
      port("Out 12", "power", "output"),
    ],
  },
  {
    id: "c0a80101-003d-4000-8000-000000000061",
    deviceType: "power-distribution",
    label: "PowerCON Distro",
    searchTerms: ["powercon", "distro", "power distribution", "show power", "edison"],
    ports: [
      port("Power In", "power", "input", "powercon"),
      port("Out 1", "power", "output", "edison"),
      port("Out 2", "power", "output", "edison"),
      port("Out 3", "power", "output", "edison"),
      port("Out 4", "power", "output", "edison"),
      port("Out 5", "power", "output", "edison"),
      port("Out 6", "power", "output", "edison"),
    ],
  },
  {
    id: "c0a80101-003e-4000-8000-000000000062",
    deviceType: "power-distribution",
    label: "PowerCON Thru Distro",
    searchTerms: ["powercon", "distro", "thru", "daisy chain", "lighting power"],
    ports: [
      port("Power In", "power", "input", "powercon"),
      port("Power Thru", "power", "output", "powercon"),
      port("Out 1", "power", "output", "powercon"),
      port("Out 2", "power", "output", "powercon"),
      port("Out 3", "power", "output", "powercon"),
      port("Out 4", "power", "output", "powercon"),
      port("Out 5", "power", "output", "powercon"),
      port("Out 6", "power", "output", "powercon"),
    ],
  },
  // Patch Panels
  {
    id: "c0a80101-00e8-4000-8000-000000000308",
    deviceType: "patch-panel",
    label: "Patch Panel 12-Port",
    searchTerms: ["patch panel", "patch bay", "12 port", "rj45", "ethernet", "cat6"],
    ports: ports("Port", "ethernet", "bidirectional", 12),
  },
  {
    id: "c0a80101-00e9-4000-8000-000000000309",
    deviceType: "patch-panel",
    label: "Patch Panel 24-Port",
    searchTerms: ["patch panel", "patch bay", "24 port", "rj45", "ethernet", "cat6"],
    ports: ports("Port", "ethernet", "bidirectional", 24),
  },
  {
    id: "c0a80101-00ea-4000-8000-000000000310",
    deviceType: "patch-panel",
    label: "Patch Panel 48-Port",
    searchTerms: ["patch panel", "patch bay", "48 port", "rj45", "ethernet", "cat6"],
    ports: ports("Port", "ethernet", "bidirectional", 48),
  },
  {
    id: "c0a80101-00eb-4000-8000-000000000311",
    deviceType: "patch-panel",
    label: "BNC Patch Panel 12-Port",
    searchTerms: ["patch panel", "patch bay", "12 port", "bnc", "sdi", "video"],
    ports: ports("Port", "sdi", "bidirectional", 12),
  },
  {
    id: "c0a80101-00ec-4000-8000-000000000312",
    deviceType: "patch-panel",
    label: "BNC Patch Panel 24-Port",
    searchTerms: ["patch panel", "patch bay", "24 port", "bnc", "sdi", "video"],
    ports: ports("Port", "sdi", "bidirectional", 24),
  },
  {
    id: "c0a80101-00ed-4000-8000-000000000313",
    deviceType: "patch-panel",
    label: "XLR Patch Panel 12-Port",
    searchTerms: ["patch panel", "patch bay", "12 port", "xlr", "audio", "analog"],
    ports: ports("Port", "analog-audio", "bidirectional", 12),
  },
  {
    id: "c0a80101-00ee-4000-8000-000000000314",
    deviceType: "patch-panel",
    label: "XLR Patch Panel 24-Port",
    searchTerms: ["patch panel", "patch bay", "24 port", "xlr", "audio", "analog"],
    ports: ports("Port", "analog-audio", "bidirectional", 24),
  },
  {
    id: "c0a80101-00ef-4000-8000-000000000315",
    deviceType: "patch-panel",
    label: "Fiber Patch Panel 12-Port",
    searchTerms: ["patch panel", "patch bay", "12 port", "fiber", "lc", "optical"],
    ports: ports("Port", "fiber", "bidirectional", 12),
  },
  {
    id: "c0a80101-00f0-4000-8000-000000000316",
    deviceType: "patch-panel",
    label: "Fiber Patch Panel 24-Port",
    searchTerms: ["patch panel", "patch bay", "24 port", "fiber", "lc", "optical"],
    ports: ports("Port", "fiber", "bidirectional", 24),
  },
];
