import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // ── LED Processors ───────────────────────────────────────────────
  {
    id: "c0a80101-00b3-4000-8000-000000000179",
    deviceType: "led-processor",
    label: "Brompton Tessera SX40",
    manufacturer: "Brompton Technology",
    modelNumber: "Tessera SX40",
    referenceUrl: "https://www.bromptontech.com/product/sx40/",
    searchTerms: ["brompton", "tessera", "sx40", "led processor", "led wall"],
    powerDrawW: 250, // typical
    ports: [
      port("12G-SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("Genlock In", "genlock", "input"),
      port("LED Out 1", "ethernet", "output", "opticalcon"),
      port("LED Out 2", "ethernet", "output", "opticalcon"),
      port("LED Out 3", "ethernet", "output", "opticalcon"),
      port("LED Out 4", "ethernet", "output", "opticalcon"),
      port("LED Out 5", "ethernet", "output", "ethercon"),
      port("LED Out 6", "ethernet", "output", "ethercon"),
      port("LED Out 7", "ethernet", "output", "ethercon"),
      port("LED Out 8", "ethernet", "output", "ethercon"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00b4-4000-8000-000000000180",
    deviceType: "led-processor",
    label: "Brompton Tessera S4",
    manufacturer: "Brompton Technology",
    modelNumber: "Tessera S4",
    referenceUrl: "https://www.bromptontech.com/product/s4/",
    searchTerms: ["brompton", "tessera", "s4", "led processor"],
    powerDrawW: 60, // typical
    ports: [
      port("DVI-D In", "hdmi", "input", "dvi"),
      port("LED Out 1", "ethernet", "output", "rj45"),
      port("LED Out 2", "ethernet", "output", "rj45"),
      port("LED Out 3", "ethernet", "output", "rj45"),
      port("LED Out 4", "ethernet", "output", "rj45"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00b5-4000-8000-000000000181",
    deviceType: "led-processor",
    label: "Brompton Tessera M2",
    manufacturer: "Brompton Technology",
    modelNumber: "Tessera M2",
    referenceUrl: "https://www.bromptontech.com/product/r2-plus/",
    searchTerms: ["brompton", "tessera", "m2", "receiver card", "led"],
    powerDrawW: 5, // typical — powered via LED panel
    ports: [
      port("LED Data In", "ethernet", "input"),
      port("LED Data Link", "ethernet", "output"),
    ],
  },
  {
    id: "c0a80101-00b6-4000-8000-000000000182",
    deviceType: "led-processor",
    label: "Novastar NovaPro HD",
    manufacturer: "Novastar",
    modelNumber: "NovaPro HD",
    referenceUrl: "https://www.novastar.tech/product/detail.html?catid=3&id=36",
    searchTerms: ["novastar", "novapro", "led processor", "led wall"],
    powerDrawW: 120, // typical
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("DVI In", "hdmi", "input", "dvi"),
      port("DP In", "displayport", "input"),
      port("VGA In", "vga", "input"),
      port("Composite In", "composite", "input"),
      port("Genlock In", "genlock", "input"),
      port("Audio In", "analog-audio", "input", "trs-eighth"),
      port("LED Out 1", "ethernet", "output"),
      port("LED Out 2", "ethernet", "output"),
      port("LED Out 3", "ethernet", "output"),
      port("LED Out 4", "ethernet", "output"),
      port("Fiber Out 1", "fiber", "output", "lc"),
      port("Fiber Out 2", "fiber", "output", "lc"),
      port("Fiber Out 3", "fiber", "output", "lc"),
      port("Fiber Out 4", "fiber", "output", "lc"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00b7-4000-8000-000000000183",
    deviceType: "led-processor",
    label: "Novastar VX2000 Pro",
    manufacturer: "Novastar",
    modelNumber: "VX2000 Pro",
    referenceUrl: "https://www.novastar.tech/product/detail.html?catid=3&id=34",
    searchTerms: ["novastar", "vx2000", "led processor", "all-in-one"],
    powerDrawW: 300, // typical
    ports: [
      port("HDMI 2.0 In 1", "hdmi", "input"),
      port("HDMI 2.0 In 2", "hdmi", "input"),
      port("HDMI 1.3 In 1", "hdmi", "input"),
      port("HDMI 1.3 In 2", "hdmi", "input"),
      port("HDMI 1.3 In 3", "hdmi", "input"),
      port("HDMI 1.3 In 4", "hdmi", "input"),
      port("12G-SDI In", "sdi", "input"),
      port("DP 1.2 In", "displayport", "input"),
      port("Genlock In", "genlock", "input"),
      ...ports("LED Out", "ethernet", "output", 20),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-010d-4000-8000-000000000345",
    deviceType: "led-processor",
    category: "led-processing",
    label: "Novastar NovaPro UHD Jr",
    manufacturer: "Novastar",
    modelNumber: "NovaPro UHD Jr",
    referenceUrl: "https://www.novastar.tech/product/detail.html?catid=3&id=36",
    searchTerms: ["novastar", "novapro", "uhd", "led processor"],
    powerDrawW: 150, // typical
    ports: [
      port("HDMI In 1", "hdmi", "input"),
      port("HDMI In 2", "hdmi", "input"),
      port("DP In", "displayport", "input"),
      port("SDI In", "sdi", "input"),
      port("Genlock In", "genlock", "input"),
      ...ports("LED Out", "ethernet", "output", 16),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-010e-4000-8000-000000000346",
    deviceType: "led-processor",
    category: "led-processing",
    label: "Brompton Tessera S8",
    manufacturer: "Brompton Technology",
    modelNumber: "Tessera S8",
    referenceUrl: "https://www.bromptontech.com/product/s8/",
    searchTerms: ["brompton", "tessera", "s8", "led processor"],
    powerDrawW: 120, // typical
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("DP In", "displayport", "input"),
      port("SDI In", "sdi", "input"),
      port("Genlock In", "genlock", "input"),
      port("LED Out 1", "ethernet", "output", "ethercon"),
      port("LED Out 2", "ethernet", "output", "ethercon"),
      port("LED Out 3", "ethernet", "output", "ethercon"),
      port("LED Out 4", "ethernet", "output", "ethercon"),
      port("LED Out 5", "ethernet", "output", "ethercon"),
      port("LED Out 6", "ethernet", "output", "ethercon"),
      port("LED Out 7", "ethernet", "output", "ethercon"),
      port("LED Out 8", "ethernet", "output", "ethercon"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-010f-4000-8000-000000000347",
    deviceType: "led-processor",
    category: "led-processing",
    label: "Brompton Tessera R2+",
    manufacturer: "Brompton Technology",
    modelNumber: "Tessera R2+",
    referenceUrl: "https://www.bromptontech.com/product/r2-plus/",
    searchTerms: ["brompton", "tessera", "r2", "receiver", "led"],
    powerDrawW: 5, // typical — powered via LED panel
    ports: [
      port("Data In", "ethernet", "input", "ethercon"),
      port("Data Out", "ethernet", "output", "ethercon"),
    ],
  },
  {
    id: "c0a80101-0187-4000-8000-000000000391",
    deviceType: "led-processor",
    category: "led-processing",
    label: "Brompton Tessera XD 10G",
    manufacturer: "Brompton Technology",
    modelNumber: "Tessera XD 10G",
    referenceUrl: "https://www.bromptontech.com/product/xd/",
    searchTerms: ["brompton", "tessera", "xd", "10g", "distribution", "led"],
    powerDrawW: 80, // typical
    ports: [
      port("10G Copper In", "ethernet", "input", "rj45"),
      port("10G Fiber In", "fiber", "input", "sfp"),
      port("10G Thru", "ethernet", "output", "sfp"),
      ...ports("LED Out", "ethernet", "output", 10, "rj45"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0188-4000-8000-000000000392",
    deviceType: "led-processor",
    category: "led-processing",
    label: "Megapixel HELIOS",
    manufacturer: "Megapixel",
    modelNumber: "HELIOS",
    referenceUrl: "https://megapixelvr.com/helios/",
    searchTerms: ["megapixel", "helios", "led processor", "led wall", "virtual production"],
    powerDrawW: 500, // typical
    ports: [
      port("QSFP Fiber In", "fiber", "input", "other"),
      port("HDMI In", "hdmi", "input"),
      port("DP In", "displayport", "input"),
      ...ports("SFP+ Slot", "fiber", "bidirectional", 4, "sfp"),
      ...ports("10G Fiber Out", "fiber", "output", 8, "sfp"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
];
