import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // ── Lighting Consoles ────────────────────────────────────────────
  {
    id: "c0a80101-00bc-4000-8000-000000000188",
    deviceType: "lighting-console",
    label: "ETC ColorSource 20",
    manufacturer: "ETC",
    modelNumber: "ColorSource 20",
    referenceUrl: "https://www.etcconnect.com/Products/Consoles/ColorSource/Features.aspx",
    searchTerms: ["etc", "colorsource", "lighting console", "compact"],
    powerDrawW: 100, // typical
    ports: [
      port("DMX Out", "dmx", "output"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00bd-4000-8000-000000000189",
    deviceType: "lighting-console",
    label: "Road Hog 4",
    manufacturer: "High End Systems",
    modelNumber: "Road Hog 4",
    referenceUrl: "https://www.etcconnect.com/Products/Consoles/Hog/",
    searchTerms: ["high end", "hog", "road hog", "lighting console"],
    powerDrawW: 350, // typical
    ports: [
      ...ports("DMX Out", "dmx", "output", 8),
      port("Ethernet", "ethernet", "bidirectional"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00be-4000-8000-000000000190",
    deviceType: "lighting-console",
    label: "ETC Eos Ti",
    manufacturer: "ETC",
    modelNumber: "Eos Ti",
    referenceUrl: "https://www.etcconnect.com/Products/Consoles/Eos-Family/Eos-Ti/Features.aspx",
    searchTerms: ["etc", "eos", "ti", "lighting console", "flagship"],
    powerDrawW: 500, // typical
    ports: [
      port("DMX Out 1", "dmx", "output"),
      port("DMX Out 2", "dmx", "output"),
      port("DMX Out 3", "dmx", "output"),
      port("DMX Out 4", "dmx", "output"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("DP Out 1", "displayport", "output"),
      port("DP Out 2", "displayport", "output"),
      port("DP Out 3", "displayport", "output"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00bf-4000-8000-000000000191",
    deviceType: "lighting-console",
    label: "grandMA3 light",
    manufacturer: "MA Lighting",
    modelNumber: "grandMA3 light",
    referenceUrl: "https://www.malighting.com/product/grandma3-light-4010502/",
    searchTerms: ["ma", "grandma", "grandma3", "lighting console"],
    powerDrawW: 300,
    ports: [
      port("DMX Out 1", "dmx", "output"),
      port("DMX Out 2", "dmx", "output"),
      port("DMX Out 3", "dmx", "output"),
      port("DMX Out 4", "dmx", "output"),
      port("DMX Out 5", "dmx", "output"),
      port("DMX Out 6", "dmx", "output"),
      port("DMX In", "dmx", "input"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("Ethernet 3", "ethernet", "bidirectional"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "powercon"),
    ],
  },
  // ── Lighting Fixtures ────────────────────────────────────────────
  {
    id: "c0a80101-00c0-4000-8000-000000000192",
    deviceType: "moving-light",
    label: "Martin MAC Aura XIP",
    manufacturer: "Martin",
    modelNumber: "MAC Aura XIP",
    referenceUrl: "https://www.martin.com/products/mac-aura-xip",
    searchTerms: ["martin", "mac", "aura", "xip", "moving light", "wash"],
    powerDrawW: 340,
    ports: [
      port("DMX In", "dmx", "input"),
      port("DMX Out", "dmx", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00c1-4000-8000-000000000193",
    deviceType: "moving-light",
    label: "Ayrton Diablo",
    manufacturer: "Ayrton",
    modelNumber: "Diablo",
    referenceUrl: "https://www.ayrton.eu/produit/diablo/",
    searchTerms: ["ayrton", "diablo", "moving light", "profile", "spot"],
    powerDrawW: 550,
    ports: [
      port("DMX In", "dmx", "input"),
      port("DMX Out", "dmx", "output"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00c2-4000-8000-000000000194",
    deviceType: "led-fixture",
    label: "Chroma-Q Color Force 72",
    manufacturer: "Chroma-Q",
    modelNumber: "Color Force 72",
    referenceUrl: "https://chroma-q.com/products/color-force-ii-72/",
    searchTerms: ["chroma-q", "color force", "led wash", "cyclorama"],
    powerDrawW: 400, // typical
    ports: [
      port("DMX In", "dmx", "input"),
      port("DMX Out", "dmx", "output"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00c3-4000-8000-000000000195",
    deviceType: "led-fixture",
    label: "ETC ColorSource Spot",
    manufacturer: "ETC",
    modelNumber: "ColorSource Spot",
    referenceUrl: "https://www.etcconnect.com/Products/Entertainment-Fixtures/ColorSource-Spot/",
    searchTerms: ["etc", "colorsource", "spot", "led", "leko", "ellipsoidal"],
    powerDrawW: 150, // typical
    ports: [
      port("DMX In", "dmx", "input"),
      port("DMX Out", "dmx", "output"),
      port("Power In", "power", "input", "powercon"),
    
      port("Power Thru", "power", "output", "powercon"),
    ],
  },
  {
    id: "c0a80101-00c4-4000-8000-000000000196",
    deviceType: "led-fixture",
    label: "Chauvet Freedom Flex H4",
    manufacturer: "Chauvet Professional",
    modelNumber: "Freedom Flex H4",
    referenceUrl: "https://www.chauvetprofessional.com/products/freedom-flex-h4/",
    searchTerms: ["chauvet", "freedom", "battery", "wireless", "led par", "uplight"],
    powerDrawW: 50, // typical
    ports: [
      port("DMX In", "dmx", "input"),
      port("DMX Out", "dmx", "output"),
    ],
  },
  {
    id: "c0a80101-00c5-4000-8000-000000000197",
    deviceType: "led-fixture",
    label: "Litepanels Astra 1x1",
    manufacturer: "Litepanels",
    modelNumber: "Astra 1x1",
    referenceUrl: "https://www.litepanels.com/en/products",
    searchTerms: ["litepanels", "astra", "led panel", "soft light", "bi-color"],
    powerDrawW: 75, // typical
    ports: [
      port("DMX In", "dmx", "input"),
      port("Power In", "power", "input", "barrel"),
    ],
  },
  // ── DMX Control ──────────────────────────────────────────────────
  {
    id: "c0a80101-00c6-4000-8000-000000000198",
    deviceType: "dmx-splitter",
    label: "DMX Opto-Splitter",
    searchTerms: ["dmx", "splitter", "opto", "distribution", "isolated"],
    powerDrawW: 15, // typical
    ports: [
      port("DMX In", "dmx", "input"),
      ...ports("DMX Out", "dmx", "output", 6),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00c7-4000-8000-000000000199",
    deviceType: "dmx-splitter",
    label: "DMX-over-Ethernet Node",
    searchTerms: ["dmx", "artnet", "sacn", "node", "gateway", "ethernet"],
    powerDrawW: 30, // typical
    ports: [
      port("Ethernet", "ethernet", "bidirectional"),
      ...ports("DMX Out", "dmx", "output", 4),
      port("DMX In 1", "dmx", "input"),
      port("DMX In 2", "dmx", "input"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0110-4000-8000-000000000348",
    deviceType: "lighting-console",
    category: "lighting",
    label: "ETC Eos Apex",
    manufacturer: "ETC",
    modelNumber: "Eos Apex",
    referenceUrl: "https://www.etcconnect.com/Products/Consoles/Eos-Consoles/",
    searchTerms: ["etc", "eos", "apex", "lighting console"],
    powerDrawW: 500, // typical
    ports: [
      port("DMX Out 1", "dmx", "output"),
      port("DMX Out 2", "dmx", "output"),
      port("DMX Out 3", "dmx", "output"),
      port("DMX Out 4", "dmx", "output"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("DP Out 1", "displayport", "output"),
      port("DP Out 2", "displayport", "output"),
      port("DP Out 3", "displayport", "output"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0111-4000-8000-000000000349",
    deviceType: "lighting-console",
    category: "lighting",
    label: "grandMA3 full-size",
    manufacturer: "MA Lighting",
    modelNumber: "grandMA3 full-size",
    referenceUrl: "https://www.malighting.com/grandma3/",
    searchTerms: ["ma", "grandma3", "full", "lighting console"],
    powerDrawW: 600, // typical
    ports: [
      ...ports("DMX Out", "dmx", "output", 8),
      port("DMX In", "dmx", "input"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("Ethernet 3", "ethernet", "bidirectional"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-0112-4000-8000-000000000350",
    deviceType: "lighting-console",
    category: "lighting",
    label: "grandMA3 compact XT",
    manufacturer: "MA Lighting",
    modelNumber: "grandMA3 compact XT",
    referenceUrl: "https://www.malighting.com/grandma3/",
    searchTerms: ["ma", "grandma3", "compact", "xt", "lighting console"],
    powerDrawW: 400, // typical
    ports: [
      ...ports("DMX Out", "dmx", "output", 6),
      port("DMX In", "dmx", "input"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("Ethernet 3", "ethernet", "bidirectional"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-0114-4000-8000-000000000352",
    deviceType: "moving-light",
    category: "lighting",
    label: "Martin MAC Ultra Performance",
    manufacturer: "Martin",
    modelNumber: "MAC Ultra Performance",
    referenceUrl: "https://www.martin.com/products/mac-ultra-performance",
    searchTerms: ["martin", "mac ultra", "moving light", "performance"],
    powerDrawW: 1450,
    ports: [
      port("DMX In", "dmx", "input"),
      port("DMX Out", "dmx", "output"),
      port("Ethernet", "ethernet", "bidirectional", "ethercon"),
      port("Power In", "power", "input", "powercon"),
    ],
  },

  // ── Additional Lighting Consoles ─────────────────────────────────
  {
    id: "c0a80101-01f5-4000-8000-000000000501",
    deviceType: "lighting-console",
    label: "grandMA2 full-size",
    manufacturer: "MA Lighting",
    modelNumber: "grandMA2 full-size",
    referenceUrl:
      "https://www.malighting.com/product-archive/product/grandma2-full-size-120111/",
    searchTerms: ["ma", "grandma", "grandma2", "lighting console"],
    powerDrawW: 350,
    ports: [
      ...ports("DMX Out", "dmx", "output", 6),
      port("DMX In", "dmx", "input"),
      port("Ethernet 1", "ethernet", "bidirectional", "ethercon"),
      port("Ethernet 2", "ethernet", "bidirectional", "ethercon"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-01f6-4000-8000-000000000502",
    deviceType: "lighting-console",
    label: "MA NPU",
    manufacturer: "MA Lighting",
    modelNumber: "MA NPU (Network Processing Unit)",
    referenceUrl:
      "https://www.malighting.com/product-archive/product/ma-npu-network-processing-unit-130032/",
    searchTerms: ["ma", "npu", "network processing unit", "dmx node"],
    powerDrawW: 150,
    ports: [
      ...ports("DMX Out", "dmx", "output", 8, "xlr-5"),
      port("Ethernet", "ethernet", "bidirectional", "ethercon"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-01f7-4000-8000-000000000503",
    deviceType: "lighting-console",
    label: "MA onPC command wing",
    manufacturer: "MA Lighting",
    modelNumber: "MA onPC command wing",
    referenceUrl:
      "https://www.malighting.com/product-archive/product/ma-onpc-command-wing-120120/",
    searchTerms: ["ma", "grandma2", "onpc", "command wing", "lighting console"],
    powerDrawW: 40,
    ports: [
      ...ports("DMX Out", "dmx", "output", 2),
      port("DMX In", "dmx", "input"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "iec"),
    ],
  },
  {
    id: "c0a80101-01f8-4000-8000-000000000504",
    deviceType: "lighting-console",
    label: "Avolites Arena",
    manufacturer: "Avolites",
    modelNumber: "Arena",
    referenceUrl: "https://www.avolites.com/product/arena/",
    searchTerms: ["avolites", "arena", "titan", "lighting console"],
    powerDrawW: 300, // typical
    ports: [
      ...ports("DMX Out", "dmx", "output", 8),
      port("Ethernet 1", "ethernet", "bidirectional", "ethercon"),
      port("Ethernet 2", "ethernet", "bidirectional", "ethercon"),
      port("Ethernet 3", "ethernet", "bidirectional", "ethercon"),
      port("Ethernet 4", "ethernet", "bidirectional", "ethercon"),
      port("Ethernet 5", "ethernet", "bidirectional", "ethercon"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("MIDI Thru", "midi", "output", "din-5"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-01f9-4000-8000-000000000505",
    deviceType: "lighting-console",
    label: "ETC Element 2",
    manufacturer: "ETC",
    modelNumber: "Element 2",
    referenceUrl:
      "https://www.etcconnect.com/Products/Consoles/Eos-Consoles/Element/Features.aspx",
    searchTerms: ["etc", "element", "element 2", "lighting console"],
    powerDrawW: 100, // typical
    ports: [
      port("DMX Out 1", "dmx", "output"),
      port("DMX Out 2", "dmx", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "iec"),
    ],
  },
  {
    id: "c0a80101-01fa-4000-8000-000000000506",
    deviceType: "lighting-console",
    label: "ETC Gio @5",
    manufacturer: "ETC",
    modelNumber: "Gio @5",
    referenceUrl:
      "https://www.etcconnect.com/Products/Consoles/Eos-Consoles/Gio-@5/Tech-Specs.aspx",
    searchTerms: ["etc", "gio", "gio @5", "eos", "lighting console"],
    powerDrawW: 300, // typical
    ports: [
      port("DMX Out 1", "dmx", "output"),
      port("DMX Out 2", "dmx", "output"),
      port("DMX Out 3", "dmx", "output"),
      port("DMX Out 4", "dmx", "output"),
      port("Ethernet 1", "ethernet", "bidirectional", "ethercon"),
      port("Ethernet 2", "ethernet", "bidirectional", "ethercon"),
      port("Ethernet 3", "ethernet", "bidirectional"),
      port("Ethernet 4", "ethernet", "bidirectional"),
      port("DP Out 1", "displayport", "output"),
      port("DP Out 2", "displayport", "output"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "iec"),
    ],
  },
  {
    id: "c0a80101-01fb-4000-8000-000000000507",
    deviceType: "lighting-console",
    label: "ETC Ion Xe",
    manufacturer: "ETC",
    modelNumber: "Ion Xe",
    referenceUrl:
      "https://www.etcconnect.com/Products/Consoles/Eos-Consoles/Ion-Xe/Tech-Specs.aspx",
    searchTerms: ["etc", "ion", "ion xe", "eos", "lighting console"],
    powerDrawW: 200, // typical
    ports: [
      port("DMX Out 1", "dmx", "output"),
      port("DMX Out 2", "dmx", "output"),
      port("DMX Out 3", "dmx", "output"),
      port("DMX Out 4", "dmx", "output"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("DP Out 1", "displayport", "output"),
      port("DP Out 2", "displayport", "output"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "iec"),
    ],
  },
  {
    id: "c0a80101-01fc-4000-8000-000000000508",
    deviceType: "lighting-console",
    label: "ETC Ion Xe 20",
    manufacturer: "ETC",
    modelNumber: "Ion Xe 20",
    referenceUrl:
      "https://www.etcconnect.com/Products/Consoles/Eos-Consoles/Ion-Xe/Tech-Specs.aspx",
    searchTerms: ["etc", "ion", "ion xe", "ion xe 20", "eos", "lighting console"],
    powerDrawW: 200, // typical
    ports: [
      port("DMX Out 1", "dmx", "output"),
      port("DMX Out 2", "dmx", "output"),
      port("DMX Out 3", "dmx", "output"),
      port("DMX Out 4", "dmx", "output"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("DP Out 1", "displayport", "output"),
      port("DP Out 2", "displayport", "output"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "iec"),
    ],
  },
  {
    id: "c0a80101-01fd-4000-8000-000000000509",
    deviceType: "lighting-console",
    label: "ETCnomad Puck",
    manufacturer: "ETC",
    modelNumber: "ETCnomad Puck",
    referenceUrl:
      "https://www.etcconnect.com/Products/Consoles/Eos-Family/ETCnomad-ETCnomad-Puck/ETCnomad-Puck.aspx",
    searchTerms: ["etc", "nomad", "etcnomad", "puck", "lighting console"],
    powerDrawW: 30, // typical
    ports: [
      port("Ethernet", "ethernet", "bidirectional"),
      port("HDMI Out", "hdmi", "output"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "iec"),
    ],
  },
  {
    id: "c0a80101-01fe-4000-8000-000000000510",
    deviceType: "dmx-splitter",
    label: "ETC Net3 4-Port Gateway",
    manufacturer: "ETC",
    modelNumber: "Net3 4-Port Gateway",
    referenceUrl:
      "https://www.etcconnect.com/Products/Legacy/Networking/Net3-4-Port-Gateway/Features.aspx",
    searchTerms: ["etc", "net3", "gateway", "sacn", "dmx node"],
    powerDrawW: 30, // typical
    ports: [
      ...ports("DMX Out", "dmx", "output", 4),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-01ff-4000-8000-000000000511",
    deviceType: "lighting-console",
    label: "ETC Universal Fader Wing",
    manufacturer: "ETC",
    modelNumber: "Universal Fader Wing",
    referenceUrl:
      "https://www.etcconnect.com/Products/Consoles/Eos-Consoles/Accessories/Fader-Wings.aspx",
    searchTerms: ["etc", "fader wing", "eos", "wing", "lighting console"],
    powerDrawW: 15, // typical
    ports: [
      port("USB", "usb", "bidirectional", "usb-b"),
      port("DC Power", "power", "input", "barrel"),
    ],
  },
  {
    id: "c0a80101-0200-4000-8000-000000000512",
    deviceType: "lighting-console",
    label: "Full Boar 4",
    manufacturer: "High End Systems",
    modelNumber: "Full Boar 4",
    referenceUrl:
      "https://www.etcconnect.com/Products/High-End-Systems/Hog-4-Consoles/Full-Boar-4/Features.aspx",
    searchTerms: ["high end", "hog", "full boar", "hog 4", "lighting console"],
    powerDrawW: 350, // typical
    ports: [
      ...ports("DMX Out", "dmx", "output", 4),
      port("HogNet", "ethernet", "bidirectional", "ethercon"),
      port("FixtureNet", "ethernet", "bidirectional", "ethercon"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "iec"),
    ],
  },
  {
    id: "c0a80101-0201-4000-8000-000000000513",
    deviceType: "lighting-console",
    label: "HedgeHog 4X",
    manufacturer: "High End Systems",
    modelNumber: "HedgeHog 4X",
    referenceUrl:
      "https://www.etcconnect.com/Products/High-End-Systems/Hog-4-Consoles/Hedgehog-4/Features.aspx",
    searchTerms: [
      "high end",
      "hedgehog",
      "hog",
      "hog 4",
      "lighting console",
    ],
    powerDrawW: 200, // typical
    ports: [
      port("DMX Out 1", "dmx", "output"),
      port("DMX Out 2", "dmx", "output"),
      port("HogNet", "ethernet", "bidirectional"),
      port("FixtureNet", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "iec"),
    ],
  },
  {
    id: "c0a80101-0202-4000-8000-000000000514",
    deviceType: "dmx-splitter",
    label: "DMX Processor 8000",
    manufacturer: "High End Systems",
    modelNumber: "DMX Processor 8000",
    referenceUrl: "https://www.etcconnect.com/DP8K.aspx",
    searchTerms: ["high end", "dp8k", "dmx processor", "hog", "dmx node"],
    powerDrawW: 60, // typical
    ports: [
      ...ports("DMX Out", "dmx", "output", 8),
      port("HogNet", "ethernet", "bidirectional", "ethercon"),
      port("FixtureNet", "ethernet", "bidirectional", "ethercon"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "iec"),
    ],
  },
  {
    id: "c0a80101-0203-4000-8000-000000000515",
    deviceType: "lighting-console",
    label: "Vari-Lite FLX S24",
    manufacturer: "Zero 88 / Vari-Lite",
    modelNumber: "FLX S24",
    referenceUrl: "https://www.vari-lite.com/global/products/flx-s24",
    searchTerms: [
      "zero 88",
      "vari-lite",
      "flx",
      "flx s24",
      "zeros",
      "lighting console",
    ],
    powerDrawW: 50, // typical
    ports: [
      port("DMX Out 1", "dmx", "output"),
      port("DMX Out 2", "dmx", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("DC Power", "power", "input", "barrel"),
    ],
  },
  {
    id: "c0a80101-0204-4000-8000-000000000516",
    deviceType: "lighting-console",
    label: "Follow-Me Mouse Console",
    manufacturer: "Follow-Me",
    modelNumber: "Mouse Console",
    referenceUrl:
      "https://follow-me.com/hardware-product/follow-me-mouse-console/",
    searchTerms: [
      "follow-me",
      "follow me",
      "mouse",
      "follow spot",
      "tracking",
      "lighting console",
    ],
    powerDrawW: 15, // typical
    ports: [
      port("Ethernet (PoE)", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0205-4000-8000-000000000517",
    deviceType: "lighting-console",
    label: "Follow-Me Fader Console",
    manufacturer: "Follow-Me",
    modelNumber: "Fader Console",
    referenceUrl:
      "https://follow-me.com/hardware-product/follow-me-fader-console/",
    searchTerms: [
      "follow-me",
      "follow me",
      "fader",
      "follow spot",
      "tracking",
      "lighting console",
    ],
    powerDrawW: 5, // typical
    ports: [
      port("Link In", "custom", "input", "xlr-5"),
    ],
  },

  // ── Additional Moving Lights ─────────────────────────────────────
  {
    id: "c0a80101-0206-4000-8000-000000000518",
    deviceType: "moving-light",
    label: "Elation Proteus Hybrid",
    manufacturer: "Elation",
    modelNumber: "Proteus Hybrid",
    referenceUrl: "https://www.elationlighting.com/products/proteus-hybrid",
    searchTerms: [
      "elation",
      "proteus",
      "hybrid",
      "ip65",
      "moving light",
      "beam",
      "spot",
      "wash",
    ],
    powerDrawW: 700,
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Ethernet In", "ethernet", "bidirectional", "ethercon"),
      port("Ethernet Out", "ethernet", "bidirectional", "ethercon"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-0207-4000-8000-000000000519",
    deviceType: "moving-light",
    label: "Elation Proteus Maximus",
    manufacturer: "Elation",
    modelNumber: "Proteus Maximus",
    referenceUrl: "https://www.elationlighting.com/products/proteus-maximus",
    searchTerms: [
      "elation",
      "proteus",
      "maximus",
      "ip65",
      "moving light",
      "profile",
    ],
    powerDrawW: 1400,
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Ethernet In", "ethernet", "bidirectional", "ethercon"),
      port("Ethernet Out", "ethernet", "bidirectional", "ethercon"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-0208-4000-8000-000000000520",
    deviceType: "moving-light",
    label: "Elation Artiste Mondrian",
    manufacturer: "Elation",
    modelNumber: "Artiste Mondrian",
    referenceUrl: "https://www.elationlighting.com/artiste-mondrian",
    searchTerms: [
      "elation",
      "artiste",
      "mondrian",
      "moving light",
      "profile",
    ],
    powerDrawW: 1500,
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-0209-4000-8000-000000000521",
    deviceType: "moving-light",
    label: "Ayrton Huracán LT",
    manufacturer: "Ayrton",
    modelNumber: "Huracán LT",
    referenceUrl: "https://www.ayrton.eu/produit/huracan-lt/",
    searchTerms: [
      "ayrton",
      "huracan",
      "lt",
      "moving light",
      "profile",
    ],
    powerDrawW: 1470,
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-020a-4000-8000-000000000522",
    deviceType: "moving-light",
    label: "Ayrton Perseo Beam",
    manufacturer: "Ayrton",
    modelNumber: "Perseo Beam",
    referenceUrl: "https://www.ayrton.eu/produit/perseo-beam/",
    searchTerms: [
      "ayrton",
      "perseo",
      "beam",
      "ip65",
      "moving light",
    ],
    powerDrawW: 700,
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Ethernet In", "ethernet", "bidirectional", "ethercon"),
      port("Ethernet Out", "ethernet", "bidirectional", "ethercon"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-020b-4000-8000-000000000523",
    deviceType: "moving-light",
    label: "Chauvet Maverick MK3 Spot",
    manufacturer: "Chauvet Professional",
    modelNumber: "Maverick MK3 Spot",
    referenceUrl:
      "https://www.chauvetprofessional.com/products/maverick-mk3-spot/",
    searchTerms: [
      "chauvet",
      "maverick",
      "mk3",
      "spot",
      "moving light",
    ],
    powerDrawW: 1180,
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Ethernet In", "ethernet", "bidirectional"),
      port("Ethernet Out", "ethernet", "bidirectional"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-020c-4000-8000-000000000524",
    deviceType: "moving-light",
    label: "Chauvet Rogue Outcast 2X Wash",
    manufacturer: "Chauvet Professional",
    modelNumber: "Rogue Outcast 2X Wash",
    referenceUrl:
      "https://www.chauvetprofessional.com/products/rogue-outcast-2-x-wash/",
    searchTerms: [
      "chauvet",
      "rogue",
      "outcast",
      "wash",
      "ip65",
      "moving light",
    ],
    powerDrawW: 291,
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-020d-4000-8000-000000000525",
    deviceType: "led-fixture",
    label: "Chauvet Color STRIKE M",
    manufacturer: "Chauvet Professional",
    modelNumber: "Color STRIKE M",
    referenceUrl:
      "https://www.chauvetprofessional.com/products/color-strike-m/",
    searchTerms: [
      "chauvet",
      "color strike",
      "strobe",
      "wash",
      "ip65",
      "blinder",
    ],
    powerDrawW: 740,
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Ethernet In", "ethernet", "bidirectional", "ethercon"),
      port("Ethernet Out", "ethernet", "bidirectional", "ethercon"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-020e-4000-8000-000000000526",
    deviceType: "moving-light",
    label: "Clay Paky Scenius Unico",
    manufacturer: "Clay Paky",
    modelNumber: "Scenius Unico",
    referenceUrl: "https://www.claypaky.it/products/scenius-unico/",
    searchTerms: [
      "clay paky",
      "claypaky",
      "scenius",
      "unico",
      "moving light",
      "hybrid",
    ],
    powerDrawW: 1000, // typical
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-020f-4000-8000-000000000527",
    deviceType: "led-fixture",
    label: "GLP JDC1",
    manufacturer: "GLP",
    modelNumber: "JDC1",
    referenceUrl:
      "https://glp.de/en/products/entertainment-lighting/strobes/jdc1-en",
    searchTerms: ["glp", "jdc1", "strobe", "led", "blinder"],
    powerDrawW: 1200,
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-0210-4000-8000-000000000528",
    deviceType: "moving-light",
    label: "GLP impression X4 Bar 20",
    manufacturer: "GLP",
    modelNumber: "impression X4 Bar 20",
    referenceUrl:
      "https://glp.de/en/products/entertainment-lighting/moving-lights/impression-x4-bar-20-en",
    searchTerms: [
      "glp",
      "impression",
      "x4",
      "bar",
      "moving light",
      "batten",
      "wash",
    ],
    powerDrawW: 400,
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Power In", "power", "input", "powercon"),
      port("Power Out", "power", "output", "powercon"),
    ],
  },
  {
    id: "c0a80101-0211-4000-8000-000000000529",
    deviceType: "moving-light",
    label: "High End SolaFrame 3000",
    manufacturer: "High End Systems",
    modelNumber: "SolaFrame 3000",
    referenceUrl:
      "https://www.etcconnect.com/Products/High-End-Systems/Lighting-Fixtures/SolaFrame/3000/Features.aspx",
    searchTerms: [
      "high end",
      "solaframe",
      "3000",
      "moving light",
      "profile",
    ],
    powerDrawW: 1100, // typical
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-0212-4000-8000-000000000530",
    deviceType: "moving-light",
    label: "High End SolaHyBeam 3000",
    manufacturer: "High End Systems",
    modelNumber: "SolaHyBeam 3000",
    referenceUrl:
      "https://www.etcconnect.com/Products/High-End-Systems/Lighting-Fixtures/SolaHybeam/3000/Features.aspx",
    searchTerms: [
      "high end",
      "solahybeam",
      "3000",
      "moving light",
      "beam",
      "hybrid",
    ],
    powerDrawW: 850, // typical
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-0213-4000-8000-000000000531",
    deviceType: "moving-light",
    label: "High End Lonestar",
    manufacturer: "High End Systems",
    modelNumber: "Lonestar",
    referenceUrl: "https://www.etcconnect.com/Lonestar/",
    searchTerms: [
      "high end",
      "lonestar",
      "moving light",
      "profile",
    ],
    powerDrawW: 800, // typical
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Ethernet 1", "ethernet", "bidirectional", "ethercon"),
      port("Ethernet 2", "ethernet", "bidirectional", "ethercon"),
      port("Power In", "power", "input", "powercon"),
    ],
  },

  // ── Additional LED Fixtures ──────────────────────────────────────
  {
    id: "c0a80101-0214-4000-8000-000000000532",
    deviceType: "led-fixture",
    label: "ARRI SkyPanel S60-C",
    manufacturer: "ARRI",
    modelNumber: "SkyPanel S60-C",
    referenceUrl:
      "https://www.arri.com/en/lighting/led-spotlights/discontinued/s60-c",
    searchTerms: [
      "arri",
      "skypanel",
      "s60",
      "led",
      "soft light",
      "panel",
    ],
    powerDrawW: 400,
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Ethernet", "ethernet", "bidirectional", "ethercon"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-0215-4000-8000-000000000533",
    deviceType: "led-fixture",
    label: "ARRI SkyPanel S360-C",
    manufacturer: "ARRI",
    modelNumber: "SkyPanel S360-C",
    referenceUrl:
      "https://www.arri.com/en/lighting/led-panel-lights/skypanel-classic/s360-c",
    searchTerms: [
      "arri",
      "skypanel",
      "s360",
      "led",
      "soft light",
      "panel",
    ],
    powerDrawW: 1500,
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Ethernet", "ethernet", "bidirectional", "ethercon"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-0216-4000-8000-000000000534",
    deviceType: "led-fixture",
    label: "Astera Titan Tube",
    manufacturer: "Astera",
    modelNumber: "Titan Tube (FP1)",
    referenceUrl: "https://astera-led.com/products/titan/specs/",
    searchTerms: [
      "astera",
      "titan",
      "tube",
      "battery",
      "wireless",
      "led",
      "pixel",
    ],
    powerDrawW: 48,
    ports: [
      port("DC Power", "power", "input", "barrel"),
    ],
  },
  {
    id: "c0a80101-0217-4000-8000-000000000535",
    deviceType: "led-fixture",
    label: "Astera AX5 TriplePAR",
    manufacturer: "Astera",
    modelNumber: "AX5 TriplePAR",
    referenceUrl: "https://astera-led.com/products/ax5-triplepar/",
    searchTerms: [
      "astera",
      "ax5",
      "triplepar",
      "battery",
      "wireless",
      "led",
      "par",
      "uplight",
    ],
    powerDrawW: 45,
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Power In", "power", "input", "powercon"),
      port("Power Out", "power", "output", "powercon"),
    ],
  },
  {
    id: "c0a80101-0218-4000-8000-000000000536",
    deviceType: "led-fixture",
    label: "Chroma-Q Studio Force II 48",
    manufacturer: "Chroma-Q",
    modelNumber: "Studio Force II 48",
    referenceUrl: "https://chroma-q.com/en_US/products/studio-force-ii-48",
    searchTerms: [
      "chroma-q",
      "studio force",
      "led",
      "broadcast",
      "soft light",
      "batten",
    ],
    powerDrawW: 550,
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Power In", "power", "input", "powercon"),
      port("Power Out", "power", "output", "powercon"),
    ],
  },
  {
    id: "c0a80101-0219-4000-8000-000000000537",
    deviceType: "led-fixture",
    label: "ETC Source Four LED Series 2 Lustr",
    manufacturer: "ETC",
    modelNumber: "Source Four LED Series 2 Lustr",
    referenceUrl:
      "https://www.etcconnect.com/Products/Entertainment-Fixtures/Source-Four-LED-Series-2/Features.aspx",
    searchTerms: [
      "etc",
      "source four",
      "source 4",
      "led",
      "lustr",
      "leko",
      "ellipsoidal",
    ],
    powerDrawW: 160, // typical
    ports: [
      port("DMX In", "dmx", "input", "xlr-5"),
      port("DMX Out", "dmx", "output", "xlr-5"),
      port("Power In", "power", "input"),
      port("Power Thru", "power", "output"),
    ],
  },
];
