import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // ── Lighting Consoles ────────────────────────────────────────────
  {
    id: "c0a80101-00bc-4000-8000-000000000188",
    deviceType: "lighting-console",
    label: "ETC ColorSource 20",
    manufacturer: "ETC",
    modelNumber: "ColorSource 20",
    referenceUrl: "https://www.etcconnect.com/Products/Consoles/ColorSource/Features.aspx",
    searchTerms: ["etc", "colorsource", "lighting console", "compact"],
    ports: [
      port("DMX Out", "dmx", "output"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00bd-4000-8000-000000000189",
    deviceType: "lighting-console",
    label: "Road Hog 4",
    manufacturer: "High End Systems",
    modelNumber: "Road Hog 4",
    referenceUrl: "https://www.etcconnect.com/Products/Consoles/Hog/",
    searchTerms: ["high end", "hog", "road hog", "lighting console"],
    ports: [
      ...ports("DMX Out", "dmx", "output", 8),
      port("Ethernet", "ethernet", "bidirectional"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00be-4000-8000-000000000190",
    deviceType: "lighting-console",
    label: "ETC Eos Ti",
    manufacturer: "ETC",
    modelNumber: "Eos Ti",
    referenceUrl: "https://www.etcconnect.com/Products/Consoles/Eos-Family/Eos-Ti/Features.aspx",
    searchTerms: ["etc", "eos", "ti", "lighting console", "flagship"],
    ports: [
      port("DMX Out 1", "dmx", "output"),
      port("DMX Out 2", "dmx", "output"),
      port("DMX Out 3", "dmx", "output"),
      port("DMX Out 4", "dmx", "output"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("DP Out 1", "displayport", "output"),
      port("DP Out 2", "displayport", "output"),
      port("DP Out 3", "displayport", "output"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00bf-4000-8000-000000000191",
    deviceType: "lighting-console",
    label: "grandMA3 light",
    manufacturer: "MA Lighting",
    modelNumber: "grandMA3 light",
    referenceUrl: "https://www.malighting.com/product/grandma3-light-4010502/",
    searchTerms: ["ma", "grandma", "grandma3", "lighting console"],
    ports: [
      port("DMX Out 1", "dmx", "output"),
      port("DMX Out 2", "dmx", "output"),
      port("DMX Out 3", "dmx", "output"),
      port("DMX Out 4", "dmx", "output"),
      port("DMX Out 5", "dmx", "output"),
      port("DMX Out 6", "dmx", "output"),
      port("DMX In", "dmx", "input"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("Ethernet 3", "ethernet", "bidirectional"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "powercon"),
    ],
  },
  // ── Lighting Fixtures ────────────────────────────────────────────
  {
    id: "c0a80101-00c0-4000-8000-000000000192",
    deviceType: "moving-light",
    label: "Martin MAC Aura XIP",
    manufacturer: "Martin",
    modelNumber: "MAC Aura XIP",
    referenceUrl: "https://www.martin.com/products/mac-aura-xip",
    searchTerms: ["martin", "mac", "aura", "xip", "moving light", "wash"],
    ports: [
      port("DMX In", "dmx", "input"),
      port("DMX Out", "dmx", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00c1-4000-8000-000000000193",
    deviceType: "moving-light",
    label: "Ayrton Diablo",
    manufacturer: "Ayrton",
    modelNumber: "Diablo",
    referenceUrl: "https://www.ayrton.eu/produit/diablo/",
    searchTerms: ["ayrton", "diablo", "moving light", "profile", "spot"],
    ports: [
      port("DMX In", "dmx", "input"),
      port("DMX Out", "dmx", "output"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00c2-4000-8000-000000000194",
    deviceType: "led-fixture",
    label: "Chroma-Q Color Force 72",
    manufacturer: "Chroma-Q",
    modelNumber: "Color Force 72",
    referenceUrl: "https://chroma-q.com/products/color-force-ii-72/",
    searchTerms: ["chroma-q", "color force", "led wash", "cyclorama"],
    ports: [
      port("DMX In", "dmx", "input"),
      port("DMX Out", "dmx", "output"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00c3-4000-8000-000000000195",
    deviceType: "led-fixture",
    label: "ETC ColorSource Spot",
    manufacturer: "ETC",
    modelNumber: "ColorSource Spot",
    referenceUrl: "https://www.etcconnect.com/Products/Entertainment-Fixtures/ColorSource-Spot/",
    searchTerms: ["etc", "colorsource", "spot", "led", "leko", "ellipsoidal"],
    ports: [
      port("DMX In", "dmx", "input"),
      port("DMX Out", "dmx", "output"),
      port("Power In", "power", "input", "powercon"),
    
      port("Power Thru", "power", "output", "powercon"),
    ],
  },
  {
    id: "c0a80101-00c4-4000-8000-000000000196",
    deviceType: "led-fixture",
    label: "Chauvet Freedom Flex H4",
    manufacturer: "Chauvet Professional",
    modelNumber: "Freedom Flex H4",
    referenceUrl: "https://www.chauvetprofessional.com/products/freedom-flex-h4/",
    searchTerms: ["chauvet", "freedom", "battery", "wireless", "led par", "uplight"],
    ports: [
      port("DMX In", "dmx", "input"),
      port("DMX Out", "dmx", "output"),
    ],
  },
  {
    id: "c0a80101-00c5-4000-8000-000000000197",
    deviceType: "led-fixture",
    label: "Litepanels Astra 1x1",
    manufacturer: "Litepanels",
    modelNumber: "Astra 1x1",
    referenceUrl: "https://www.litepanels.com/en/products",
    searchTerms: ["litepanels", "astra", "led panel", "soft light", "bi-color"],
    ports: [
      port("DMX In", "dmx", "input"),
      port("Power In", "power", "input", "barrel"),
    ],
  },
  // ── DMX Control ──────────────────────────────────────────────────
  {
    id: "c0a80101-00c6-4000-8000-000000000198",
    deviceType: "dmx-splitter",
    label: "DMX Opto-Splitter",
    searchTerms: ["dmx", "splitter", "opto", "distribution", "isolated"],
    ports: [
      port("DMX In", "dmx", "input"),
      ...ports("DMX Out", "dmx", "output", 6),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00c7-4000-8000-000000000199",
    deviceType: "dmx-splitter",
    label: "DMX-over-Ethernet Node",
    searchTerms: ["dmx", "artnet", "sacn", "node", "gateway", "ethernet"],
    ports: [
      port("Ethernet", "ethernet", "bidirectional"),
      ...ports("DMX Out", "dmx", "output", 4),
      port("DMX In 1", "dmx", "input"),
      port("DMX In 2", "dmx", "input"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0110-4000-8000-000000000348",
    deviceType: "lighting-console",
    category: "lighting",
    label: "ETC Eos Apex",
    manufacturer: "ETC",
    modelNumber: "Eos Apex",
    referenceUrl: "https://www.etcconnect.com/Products/Consoles/Eos-Consoles/",
    searchTerms: ["etc", "eos", "apex", "lighting console"],
    ports: [
      port("DMX Out 1", "dmx", "output"),
      port("DMX Out 2", "dmx", "output"),
      port("DMX Out 3", "dmx", "output"),
      port("DMX Out 4", "dmx", "output"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("DP Out 1", "displayport", "output"),
      port("DP Out 2", "displayport", "output"),
      port("DP Out 3", "displayport", "output"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0111-4000-8000-000000000349",
    deviceType: "lighting-console",
    category: "lighting",
    label: "grandMA3 full-size",
    manufacturer: "MA Lighting",
    modelNumber: "grandMA3 full-size",
    referenceUrl: "https://www.malighting.com/grandma3/",
    searchTerms: ["ma", "grandma3", "full", "lighting console"],
    ports: [
      ...ports("DMX Out", "dmx", "output", 8),
      port("DMX In", "dmx", "input"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("Ethernet 3", "ethernet", "bidirectional"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-0112-4000-8000-000000000350",
    deviceType: "lighting-console",
    category: "lighting",
    label: "grandMA3 compact XT",
    manufacturer: "MA Lighting",
    modelNumber: "grandMA3 compact XT",
    referenceUrl: "https://www.malighting.com/grandma3/",
    searchTerms: ["ma", "grandma3", "compact", "xt", "lighting console"],
    ports: [
      ...ports("DMX Out", "dmx", "output", 6),
      port("DMX In", "dmx", "input"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("Ethernet 3", "ethernet", "bidirectional"),
      port("MIDI In", "midi", "input", "din-5"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-0114-4000-8000-000000000352",
    deviceType: "moving-light",
    category: "lighting",
    label: "Martin MAC Ultra Performance",
    manufacturer: "Martin",
    modelNumber: "MAC Ultra Performance",
    referenceUrl: "https://www.martin.com/products/mac-ultra-performance",
    searchTerms: ["martin", "mac ultra", "moving light", "performance"],
    ports: [
      port("DMX In", "dmx", "input"),
      port("DMX Out", "dmx", "output"),
      port("Ethernet", "ethernet", "bidirectional", "ethercon"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
];
