import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // ── Media Servers ────────────────────────────────────────────────
  {
    id: "c0a80101-00b8-4000-8000-000000000184",
    deviceType: "media-server",
    label: "Disguise d3 4x4pro",
    manufacturer: "Disguise",
    modelNumber: "d3 4x4pro",
    referenceUrl: "https://www.disguise.one/en/products/legacy-products/",
    searchTerms: ["disguise", "d3", "4x4pro", "media server"],
    powerDrawW: 1200, // typical
    slots: [
      { id: "d3-4x4-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-dp12", slotFamily: "disguise-vfc" },
      { id: "d3-4x4-vfc-b", label: "VFC Slot B", defaultCardId: "vfc-card-dp12", slotFamily: "disguise-vfc" },
      { id: "d3-4x4-vfc-c", label: "VFC Slot C", defaultCardId: "vfc-card-dp12", slotFamily: "disguise-vfc" },
      { id: "d3-4x4-vfc-d", label: "VFC Slot D", defaultCardId: "vfc-card-dp12", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("DMX Out", "dmx", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00b9-4000-8000-000000000185",
    deviceType: "media-server",
    label: "Disguise d3 Solo",
    manufacturer: "Disguise",
    modelNumber: "d3 Solo",
    referenceUrl: "https://www.disguise.one/en/products/legacy-products/",
    searchTerms: ["disguise", "d3", "solo", "media server", "compact"],
    powerDrawW: 500, // typical
    slots: [
      { id: "d3-solo-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-dp12", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00ba-4000-8000-000000000186",
    deviceType: "media-server",
    label: "Dataton WATCHPAX 60",
    manufacturer: "Dataton",
    modelNumber: "WATCHPAX 60",
    referenceUrl: "https://www.dataton.com/watchpax/watchpax-64",
    searchTerms: ["dataton", "watchpax", "watchout", "media server"],
    powerDrawW: 200, // typical
    ports: [
      ...ports("HDMI Out", "hdmi", "output", 4),
      port("HDMI In", "hdmi", "input"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00bb-4000-8000-000000000187",
    deviceType: "media-server",
    label: "Dataton WATCHPAX 40",
    manufacturer: "Dataton",
    modelNumber: "WATCHPAX 40",
    referenceUrl: "https://www.dataton.com/watchpax/watchpax-64",
    searchTerms: ["dataton", "watchpax", "watchout", "media server", "compact"],
    powerDrawW: 120, // typical
    ports: [
      port("HDMI Out 1", "hdmi", "output"),
      port("HDMI Out 2", "hdmi", "output"),
      port("HDMI In", "hdmi", "input"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Infrastructure new devices
  {
    id: "c0a80101-010a-4000-8000-000000000342",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise VX 4+",
    manufacturer: "Disguise",
    modelNumber: "VX 4+",
    referenceUrl: "https://www.disguise.one/en/products/vx-range/",
    searchTerms: ["disguise", "vx4", "media server", "d3"],
    powerDrawW: 1500, // typical
    slots: [
      { id: "vfc-slot-a", label: "VFC Slot A", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "vfc-slot-b", label: "VFC Slot B", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "vfc-slot-c", label: "VFC Slot C", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "vfc-slot-d", label: "VFC Slot D", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("10GbE SFP+ 1", "ethernet", "bidirectional", "sfp"),
      port("10GbE SFP+ 2", "ethernet", "bidirectional", "sfp"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-010c-4000-8000-000000000344",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise VX 1",
    manufacturer: "Disguise",
    modelNumber: "VX 1",
    referenceUrl: "https://www.disguise.one/en/products/vx-range/",
    searchTerms: ["disguise", "vx1", "media server", "d3"],
    powerDrawW: 600, // typical
    slots: [
      { id: "vx1-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-010d-4000-8000-000000000345",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise VX 2",
    manufacturer: "Disguise",
    modelNumber: "VX 2",
    referenceUrl: "https://www.disguise.one/en/products/vx-range/",
    searchTerms: ["disguise", "vx2", "media server", "d3"],
    powerDrawW: 900, // typical
    slots: [
      { id: "vx2-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "vx2-vfc-b", label: "VFC Slot B", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("10GbE SFP+ 1", "ethernet", "bidirectional", "sfp"),
      port("10GbE SFP+ 2", "ethernet", "bidirectional", "sfp"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-010e-4000-8000-000000000346",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise VX 3",
    manufacturer: "Disguise",
    modelNumber: "VX 3",
    referenceUrl: "https://www.disguise.one/en/products/vx-range/",
    searchTerms: ["disguise", "vx3", "media server", "d3"],
    powerDrawW: 1200, // typical
    slots: [
      { id: "vx3-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "vx3-vfc-b", label: "VFC Slot B", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "vx3-vfc-c", label: "VFC Slot C", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("10GbE SFP+ 1", "ethernet", "bidirectional", "sfp"),
      port("10GbE SFP+ 2", "ethernet", "bidirectional", "sfp"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-010f-4000-8000-000000000347",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise GX 1",
    manufacturer: "Disguise",
    modelNumber: "GX 1",
    referenceUrl: "https://www.disguise.one/en/products/gx-range/",
    searchTerms: ["disguise", "gx1", "media server", "gpu"],
    powerDrawW: 800, // typical
    slots: [
      { id: "gx1-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0110-4000-8000-000000000348",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise GX 2",
    manufacturer: "Disguise",
    modelNumber: "GX 2",
    referenceUrl: "https://www.disguise.one/en/products/gx-range/",
    searchTerms: ["disguise", "gx2", "media server", "gpu"],
    powerDrawW: 1200, // typical
    slots: [
      { id: "gx2-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-dp12", slotFamily: "disguise-vfc" },
      { id: "gx2-vfc-b", label: "VFC Slot B", defaultCardId: "vfc-card-dp12", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("10GbE SFP+ 1", "ethernet", "bidirectional", "sfp"),
      port("10GbE SFP+ 2", "ethernet", "bidirectional", "sfp"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0111-4000-8000-000000000349",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise GX 2C",
    manufacturer: "Disguise",
    modelNumber: "GX 2C",
    referenceUrl: "https://www.disguise.one/en/products/gx-range/",
    searchTerms: ["disguise", "gx2c", "media server", "gpu", "compact"],
    powerDrawW: 1000, // typical
    slots: [
      { id: "gx2c-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "gx2c-vfc-b", label: "VFC Slot B", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("10GbE SFP+ 1", "ethernet", "bidirectional", "sfp"),
      port("10GbE SFP+ 2", "ethernet", "bidirectional", "sfp"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0112-4000-8000-000000000350",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise GX 3",
    manufacturer: "Disguise",
    modelNumber: "GX 3",
    referenceUrl: "https://www.disguise.one/en/products/gx-range/",
    searchTerms: ["disguise", "gx3", "media server", "gpu"],
    powerDrawW: 1500, // typical
    slots: [
      { id: "gx3-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-dp14", slotFamily: "disguise-vfc" },
      { id: "gx3-vfc-b", label: "VFC Slot B", defaultCardId: "vfc-card-dp14", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("10GbE SFP+ 1", "ethernet", "bidirectional", "sfp"),
      port("10GbE SFP+ 2", "ethernet", "bidirectional", "sfp"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-010b-4000-8000-000000000343",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise EX 2",
    manufacturer: "Disguise",
    modelNumber: "EX 2",
    referenceUrl: "https://www.disguise.one/en/products/ex-range/",
    searchTerms: ["disguise", "ex2", "media server", "d3"],
    powerDrawW: 400, // typical
    ports: [
      port("DP Out 1", "displayport", "output"),
      port("DP Out 2", "displayport", "output"),
      port("NDI In", "ndi", "input"),
      port("Genlock In", "genlock", "input"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-010c-4000-8000-000000000344",
    deviceType: "media-server",
    category: "media-servers",
    label: "Dataton WATCHPAX 64",
    manufacturer: "Dataton",
    modelNumber: "WATCHPAX 64",
    referenceUrl: "https://www.dataton.com/watchpax/watchpax-64",
    searchTerms: ["dataton", "watchpax", "watchout", "media server"],
    powerDrawW: 200, // typical
    ports: [
      port("DP Out 1", "displayport", "output"),
      port("DP Out 2", "displayport", "output"),
      port("DP Out 3", "displayport", "output"),
      port("DP Out 4", "displayport", "output"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0182-4000-8000-000000000386",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise EX 3",
    manufacturer: "Disguise",
    modelNumber: "EX 3",
    referenceUrl: "https://www.disguise.one/en/products/ex-range/",
    searchTerms: ["disguise", "ex3", "media server", "playback"],
    powerDrawW: 800, // typical
    ports: [
      ...ports("DP Out", "displayport", "output", 3),
      port("Genlock In", "genlock", "input"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("10GbE 1", "ethernet", "bidirectional", "sfp"),
      port("10GbE 2", "ethernet", "bidirectional", "sfp"),
      port("25GbE 1", "ethernet", "bidirectional", "sfp"),
      port("25GbE 2", "ethernet", "bidirectional", "sfp"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0183-4000-8000-000000000387",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise EX 3+",
    manufacturer: "Disguise",
    modelNumber: "EX 3+",
    referenceUrl: "https://www.disguise.one/en/products/ex-range/",
    searchTerms: ["disguise", "ex3+", "media server", "playback"],
    powerDrawW: 1200, // typical
    ports: [
      ...ports("DP Out", "displayport", "output", 3),
      port("HDMI In", "hdmi", "input"),
      port("12G-SDI In A", "sdi", "input"),
      port("12G-SDI In C", "sdi", "input"),
      ...ports("3G-SDI In", "sdi", "input", 4),
      port("Genlock In", "genlock", "input"),
      port("100GbE QSFP28 1", "ethernet", "bidirectional", "other"),
      port("100GbE QSFP28 2", "ethernet", "bidirectional", "other"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0184-4000-8000-000000000388",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise GX 3+",
    manufacturer: "Disguise",
    modelNumber: "GX 3+",
    referenceUrl: "https://www.disguise.one/en/products/gx-range/",
    searchTerms: ["disguise", "gx3+", "media server", "gpu"],
    powerDrawW: 2000, // typical
    slots: [
      { id: "gx3p-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "gx3p-vfc-b", label: "VFC Slot B", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "gx3p-vfc-c", label: "VFC Slot C", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
    ],
    ports: [
      ...ports("12G-SDI In", "sdi", "input", 3),
      port("XLR In 1", "analog-audio", "input"),
      port("XLR In 2", "analog-audio", "input"),
      port("XLR Out 1", "analog-audio", "output"),
      port("XLR Out 2", "analog-audio", "output"),
      port("MGMT Ethernet", "ethernet", "bidirectional"),
      port("10GbE A", "ethernet", "bidirectional", "sfp"),
      port("10GbE B", "ethernet", "bidirectional", "sfp"),
      port("10GbE C", "ethernet", "bidirectional", "sfp"),
      port("10GbE D", "ethernet", "bidirectional", "sfp"),
      port("100GbE QSFP28 E", "ethernet", "bidirectional", "other"),
      port("100GbE QSFP28 F", "ethernet", "bidirectional", "other"),
      port("AC Power", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-0185-4000-8000-000000000389",
    deviceType: "media-server",
    category: "media-servers",
    label: "Follow-Me Rack Server",
    manufacturer: "Follow-Me",
    modelNumber: "Rack Server",
    referenceUrl: "https://follow-me.com/hardware-product/follow-me-rack-server/",
    searchTerms: ["follow-me", "follow me", "tracking", "follow spot", "rack server"],
    powerDrawW: 300, // typical
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("SDI In", "sdi", "input"),
      port("Ethernet", "ethernet", "bidirectional", "ethercon"),
      port("USB 1", "usb", "bidirectional", "usb-a"),
      port("USB 2", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0186-4000-8000-000000000390",
    deviceType: "media-server",
    category: "media-servers",
    label: "DT Videolabs PlaybackPro Plus",
    manufacturer: "DT Videolabs",
    modelNumber: "PlaybackPro Plus",
    referenceUrl: "https://www.dtvideolabs.com/playbackpro-plus-3/",
    searchTerms: ["dt videolabs", "playbackpro", "playback pro", "video playback"],
    powerDrawW: 100, // typical — software on Mac hardware
    ports: [
      port("HDMI Out", "hdmi", "output"),
      port("Thunderbolt", "thunderbolt", "bidirectional", "usb-c"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
];
