import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // ── Speakers & Amplifiers ────────────────────────────────────────
  {
    id: "c0a80101-00a7-4000-8000-000000000167",
    deviceType: "speaker",
    label: "Meyer Leopard",
    manufacturer: "Meyer Sound",
    modelNumber: "Leopard",
    referenceUrl: "https://meyersound.com/product/leopard/",
    searchTerms: ["meyer", "leopard", "line array", "powered"],
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00a8-4000-8000-000000000168",
    deviceType: "speaker",
    label: "L'Acoustics KIVA II",
    manufacturer: "L'Acoustics",
    modelNumber: "KIVA II",
    referenceUrl: "https://www.l-acoustics.com/products/kiva-ii/",
    searchTerms: ["l-acoustics", "kiva", "line array", "passive"],
    ports: [
      port("Input", "analog-audio", "input", "speakon"),
      port("Link", "analog-audio", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-00a9-4000-8000-000000000169",
    deviceType: "speaker",
    label: "JBL VRX928LA",
    manufacturer: "JBL Professional",
    modelNumber: "VRX928LA",
    referenceUrl: "https://jblpro.com/products/vrx928la",
    searchTerms: ["jbl", "vrx", "line array", "passive", "compact"],
    ports: [
      port("Input", "analog-audio", "input", "speakon"),
      port("Link", "analog-audio", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-00aa-4000-8000-000000000170",
    deviceType: "speaker",
    label: "Meyer UPM-1P",
    manufacturer: "Meyer Sound",
    modelNumber: "UPM-1P",
    referenceUrl: "https://meyersound.com/product/upm-1p/",
    searchTerms: ["meyer", "upm", "powered", "fill", "delay"],
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00ab-4000-8000-000000000171",
    deviceType: "speaker",
    label: "Meyer UPA-1P",
    manufacturer: "Meyer Sound",
    modelNumber: "UPA-1P",
    referenceUrl: "https://meyersound.com/product/upa-1p/",
    searchTerms: ["meyer", "upa", "powered", "loudspeaker"],
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00ac-4000-8000-000000000172",
    deviceType: "speaker",
    label: "QSC K12.2",
    manufacturer: "QSC",
    modelNumber: "K12.2",
    referenceUrl: "https://www.qsc.com/products-solutions/loudspeakers/powered-loudspeakers/k2-series/k122/",
    searchTerms: ["qsc", "k12", "k series", "powered", "portable"],
    ports: [
      port("Combo In 1", "analog-audio", "input", "combo-xlr-trs"),
      port("Combo In 2", "analog-audio", "input", "combo-xlr-trs"),
      port("Line Out", "analog-audio", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00ad-4000-8000-000000000173",
    deviceType: "speaker",
    label: "Meyer 900-LFC",
    manufacturer: "Meyer Sound",
    modelNumber: "900-LFC",
    referenceUrl: "https://meyersound.com/product/900-lfc/",
    searchTerms: ["meyer", "900", "lfc", "subwoofer", "powered"],
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00ae-4000-8000-000000000174",
    deviceType: "speaker",
    label: "L'Acoustics SB15m",
    manufacturer: "L'Acoustics",
    modelNumber: "SB15m",
    referenceUrl: "https://www.l-acoustics.com/products/sb15m/",
    searchTerms: ["l-acoustics", "sb15", "subwoofer", "passive"],
    ports: [
      port("Input", "analog-audio", "input", "speakon"),
      port("Link", "analog-audio", "output", "speakon"),
    ],
  },
  {
    id: "c0a80101-00af-4000-8000-000000000175",
    deviceType: "speaker",
    label: "Meyer MJF-210",
    manufacturer: "Meyer Sound",
    modelNumber: "MJF-210",
    referenceUrl: "https://meyersound.com/product/mjf-210/",
    searchTerms: ["meyer", "mjf", "wedge", "monitor", "stage"],
    ports: [
      port("Audio In", "analog-audio", "input"),
      port("Audio Link", "analog-audio", "output"),
      port("Power In", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00b0-4000-8000-000000000176",
    deviceType: "amplifier",
    label: "QSC PLD 4.5",
    manufacturer: "QSC",
    modelNumber: "PLD 4.5",
    referenceUrl: "https://www.qsc.com/products-solutions/power-amplifiers/installed/pld-series/pld-4-5/",
    searchTerms: ["qsc", "pld", "amplifier", "dsp", "4 channel"],
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      ...ports("Speaker Out", "analog-audio", "output", 4, "speakon"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input", "powercon"),
    ],
  },
  {
    id: "c0a80101-00b1-4000-8000-000000000177",
    deviceType: "amplifier",
    label: "L'Acoustics LA4X",
    manufacturer: "L'Acoustics",
    modelNumber: "LA4X",
    referenceUrl: "https://www.l-acoustics.com/products/la4x/",
    searchTerms: ["l-acoustics", "la4x", "amplified controller", "4 channel"],
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4),
      ...ports("Speaker Out", "analog-audio", "output", 4, "speakon"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input", "powercon"),

      port("AES In 1-2", "aes", "input"),
    
      port("AES In 3-4", "aes", "input"),
    
      port("AES Link 1-2", "aes", "output"),
    ],
  },
];
