import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // Switchers
  {
    id: "c0a80101-0002-4000-8000-000000000002",
    deviceType: "switcher",
    label: "Video Switcher",
    ports: [
      port("SDI In 1", "sdi", "input"),
      port("SDI In 2", "sdi", "input"),
      port("SDI In 3", "sdi", "input"),
      port("SDI In 4", "sdi", "input"),
      port("PGM Out", "sdi", "output"),
      port("PVW Out", "sdi", "output"),
      port("AUX Out", "sdi", "output"),
      port("Multiview", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Router
  {
    id: "c0a80101-0014-4000-8000-000000000020",
    deviceType: "router",
    label: "SDI Router",
    ports: [
      port("In 1", "sdi", "input"),
      port("In 2", "sdi", "input"),
      port("In 3", "sdi", "input"),
      port("In 4", "sdi", "input"),
      port("Out 1", "sdi", "output"),
      port("Out 2", "sdi", "output"),
      port("Out 3", "sdi", "output"),
      port("Out 4", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Blackmagic Smart Videohub 20x20
  {
    id: "c0a80101-0015-4000-8000-000000000021",
    deviceType: "router",
    label: "BMD Videohub 20x20 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Smart Videohub 20x20",
    referenceUrl: "https://www.blackmagicdesign.com/products/blackmagicvideohub/techspecs",
    searchTerms: ["blackmagic", "smart videohub", "videohub", "20x20", "matrix"],
    ports: [
      port("In 1", "sdi", "input"),
      port("In 2", "sdi", "input"),
      port("In 3", "sdi", "input"),
      port("In 4", "sdi", "input"),
      port("In 5", "sdi", "input"),
      port("In 6", "sdi", "input"),
      port("In 7", "sdi", "input"),
      port("In 8", "sdi", "input"),
      port("In 9", "sdi", "input"),
      port("In 10", "sdi", "input"),
      port("In 11", "sdi", "input"),
      port("In 12", "sdi", "input"),
      port("In 13", "sdi", "input"),
      port("In 14", "sdi", "input"),
      port("In 15", "sdi", "input"),
      port("In 16", "sdi", "input"),
      port("In 17", "sdi", "input"),
      port("In 18", "sdi", "input"),
      port("In 19", "sdi", "input"),
      port("In 20", "sdi", "input"),
      port("Out 1", "sdi", "output"),
      port("Out 2", "sdi", "output"),
      port("Out 3", "sdi", "output"),
      port("Out 4", "sdi", "output"),
      port("Out 5", "sdi", "output"),
      port("Out 6", "sdi", "output"),
      port("Out 7", "sdi", "output"),
      port("Out 8", "sdi", "output"),
      port("Out 9", "sdi", "output"),
      port("Out 10", "sdi", "output"),
      port("Out 11", "sdi", "output"),
      port("Out 12", "sdi", "output"),
      port("Out 13", "sdi", "output"),
      port("Out 14", "sdi", "output"),
      port("Out 15", "sdi", "output"),
      port("Out 16", "sdi", "output"),
      port("Out 17", "sdi", "output"),
      port("Out 18", "sdi", "output"),
      port("Out 19", "sdi", "output"),
      port("Out 20", "sdi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Ref In", "genlock", "input"),
    
      port("USB-C", "usb", "bidirectional", "usb-c"),
    ],
  },
  // Blackmagic CleanSwitch 12x12
  {
    id: "c0a80101-0016-4000-8000-000000000022",
    deviceType: "router",
    label: "BMD CleanSwitch 12x12",
    manufacturer: "Blackmagic Design",
    modelNumber: "CleanSwitch 12x12",
    referenceUrl: "https://www.blackmagicdesign.com/products/blackmagicvideohub/techspecs/W-VHS-06",
    searchTerms: ["blackmagic", "videohub", "cleanswitch", "clean switch", "12x12"],
    ports: [
      port("In 1", "sdi", "input"),
      port("In 2", "sdi", "input"),
      port("In 3", "sdi", "input"),
      port("In 4", "sdi", "input"),
      port("In 5", "sdi", "input"),
      port("In 6", "sdi", "input"),
      port("In 7", "sdi", "input"),
      port("In 8", "sdi", "input"),
      port("In 9", "sdi", "input"),
      port("In 10", "sdi", "input"),
      port("In 11", "sdi", "input"),
      port("In 12", "sdi", "input"),
      port("Out 1", "sdi", "output"),
      port("Out 2", "sdi", "output"),
      port("Out 3", "sdi", "output"),
      port("Out 4", "sdi", "output"),
      port("Out 5", "sdi", "output"),
      port("Out 6", "sdi", "output"),
      port("Out 7", "sdi", "output"),
      port("Out 8", "sdi", "output"),
      port("Out 9", "sdi", "output"),
      port("Out 10", "sdi", "output"),
      port("Out 11", "sdi", "output"),
      port("Out 12", "sdi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Ref In", "genlock", "input"),
    
      port("RS-422", "rs422", "bidirectional", "rj45"),
    ],
  },
  // Kramer VS-88H2 — 8x8 HDMI Matrix Switcher
  {
    id: "c0a80101-0017-4000-8000-000000000023",
    deviceType: "router",
    label: "Kramer VS-88H2",
    manufacturer: "Kramer",
    modelNumber: "VS-88H2",
    referenceUrl: "https://www1.kramerav.com/us/product/vs-88h2",
    searchTerms: ["kramer", "hdmi", "matrix", "8x8", "switcher"],
    ports: [
      port("HDMI In 1", "hdmi", "input"),
      port("HDMI In 2", "hdmi", "input"),
      port("HDMI In 3", "hdmi", "input"),
      port("HDMI In 4", "hdmi", "input"),
      port("HDMI In 5", "hdmi", "input"),
      port("HDMI In 6", "hdmi", "input"),
      port("HDMI In 7", "hdmi", "input"),
      port("HDMI In 8", "hdmi", "input"),
      port("HDMI Out 1", "hdmi", "output"),
      port("HDMI Out 2", "hdmi", "output"),
      port("HDMI Out 3", "hdmi", "output"),
      port("HDMI Out 4", "hdmi", "output"),
      port("HDMI Out 5", "hdmi", "output"),
      port("HDMI Out 6", "hdmi", "output"),
      port("HDMI Out 7", "hdmi", "output"),
      port("HDMI Out 8", "hdmi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Video Switchers ──────────────────────────────────────────────
  {
    id: "c0a80101-003d-4000-8000-000000000061",
    deviceType: "switcher",
    label: "ATEM Mini",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM Mini",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemmini",
    searchTerms: ["blackmagic", "atem", "mini", "hdmi switcher"],
    ports: [
      ...ports("HDMI In", "hdmi", "input", 4),
      port("HDMI Out", "hdmi", "output"),
      port("USB-C Out", "usb", "output", "usb-c"),
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
    ],
  },
  {
    id: "c0a80101-003e-4000-8000-000000000062",
    deviceType: "switcher",
    label: "ATEM Mini Pro",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM Mini Pro",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemmini",
    searchTerms: ["blackmagic", "atem", "mini pro", "streaming"],
    ports: [
      ...ports("HDMI In", "hdmi", "input", 4),
      port("HDMI Out", "hdmi", "output"),
      port("USB-C Out", "usb", "output", "usb-c"),
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-003f-4000-8000-000000000063",
    deviceType: "switcher",
    label: "ATEM Mini Pro ISO",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM Mini Pro ISO",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemmini",
    searchTerms: ["blackmagic", "atem", "mini pro iso", "recording"],
    ports: [
      ...ports("HDMI In", "hdmi", "input", 4),
      port("HDMI Out", "hdmi", "output"),
      port("USB-C Out", "usb", "output", "usb-c"),
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0040-4000-8000-000000000064",
    deviceType: "switcher",
    label: "ATEM Mini Extreme",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM Mini Extreme",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemmini",
    searchTerms: ["blackmagic", "atem", "mini extreme", "8 input"],
    ports: [
      ...ports("HDMI In", "hdmi", "input", 8),
      port("HDMI Out 1", "hdmi", "output"),
      port("HDMI Out 2", "hdmi", "output"),
      port("USB-C Out 1", "usb", "output", "usb-c"),
      port("USB-C Out 2", "usb", "output", "usb-c"),
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
      port("Headphone", "analog-audio", "output", "trs-eighth"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0041-4000-8000-000000000065",
    deviceType: "switcher",
    label: "ATEM Mini Extreme ISO",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM Mini Extreme ISO",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemmini",
    searchTerms: ["blackmagic", "atem", "mini extreme iso", "8 input", "recording"],
    ports: [
      ...ports("HDMI In", "hdmi", "input", 8),
      port("HDMI Out 1", "hdmi", "output"),
      port("HDMI Out 2", "hdmi", "output"),
      port("USB-C Out 1", "usb", "output", "usb-c"),
      port("USB-C Out 2", "usb", "output", "usb-c"),
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
      port("Headphone", "analog-audio", "output", "trs-eighth"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0042-4000-8000-000000000066",
    deviceType: "switcher",
    label: "ATEM SDI",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM SDI",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemsdi",
    searchTerms: ["blackmagic", "atem", "sdi switcher"],
    ports: [
      ...ports("SDI In", "sdi", "input", 4),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("USB-C Out", "usb", "output", "usb-c"),
    
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
    
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
    
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0043-4000-8000-000000000067",
    deviceType: "switcher",
    label: "ATEM SDI Pro ISO",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM SDI Pro ISO",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemsdi",
    searchTerms: ["blackmagic", "atem", "sdi pro iso"],
    ports: [
      ...ports("SDI In", "sdi", "input", 4),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("USB-C Out", "usb", "output", "usb-c"),
      port("Ethernet", "ethernet", "bidirectional"),
    
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
    
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
    ],
  },
  {
    id: "c0a80101-0044-4000-8000-000000000068",
    deviceType: "switcher",
    label: "ATEM SDI Extreme ISO",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM SDI Extreme ISO",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemsdi",
    searchTerms: ["blackmagic", "atem", "sdi extreme iso", "8 input"],
    ports: [
      ...ports("SDI In", "sdi", "input", 8),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("USB-C Out", "usb", "output", "usb-c"),
      port("Ethernet", "ethernet", "bidirectional"),
    
      port("SDI Out 3", "sdi", "output"),
    
      port("SDI Out 4", "sdi", "output"),
    
      port("Mic In 1", "analog-audio", "input", "trs-eighth"),
    
      port("Mic In 2", "analog-audio", "input", "trs-eighth"),
    
      port("Headphone", "analog-audio", "output", "trs-eighth"),
    
      port("USB-C Out 2", "usb", "output", "usb-c"),
    ],
  },
  {
    id: "c0a80101-0045-4000-8000-000000000069",
    deviceType: "switcher",
    label: "ATEM Television Studio HD8",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM Television Studio HD8",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemtelevisionstudio",
    searchTerms: ["blackmagic", "atem", "television studio", "hd8"],
    ports: [
      ...ports("SDI In", "sdi", "input", 8),
      port("PGM Out", "sdi", "output"),
      port("PVW Out", "sdi", "output"),
      port("AUX Out 1", "sdi", "output"),
      port("AUX Out 2", "sdi", "output"),
      port("MV SDI Out", "sdi", "output"),
      port("MV HDMI Out", "hdmi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("RS-422", "rs422", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("SDI Out 3", "sdi", "output"),
    
      port("SDI Out 4", "sdi", "output"),
    
      port("SDI Out 5", "sdi", "output"),
    
      port("SDI Out 6", "sdi", "output"),
    
      port("SDI Out 7", "sdi", "output"),
    
      port("MADI In", "madi", "input"),
    
      port("MADI Out", "madi", "output"),
    
      port("XLR In 1", "analog-audio", "input"),
    
      port("XLR In 2", "analog-audio", "input"),
    
      port("Timecode In", "genlock", "input"),
    
      port("Timecode Out", "genlock", "output"),
    
      port("Ref In", "genlock", "input"),
    
      port("Ref Out", "genlock", "output"),
    
      port("USB-C 1", "usb", "bidirectional", "usb-c"),
    
      port("USB-C 2", "usb", "bidirectional", "usb-c"),
    ],
  },
  {
    id: "c0a80101-0046-4000-8000-000000000070",
    deviceType: "switcher",
    label: "ATEM Constellation 1 M/E",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM 1 M/E Constellation HD",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemconstellation",
    searchTerms: ["blackmagic", "atem", "constellation", "1me", "12g"],
    ports: [
      ...ports("SDI In", "sdi", "input", 10),
      ...ports("SDI Out", "sdi", "output", 6),
      port("Ref In", "genlock", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Analog In L", "analog-audio", "input", "trs-quarter"),
    
      port("Analog In R", "analog-audio", "input", "trs-quarter"),
    
      port("Talkback", "analog-audio", "bidirectional", "xlr-5"),
    ],
  },
  {
    id: "c0a80101-0047-4000-8000-000000000071",
    deviceType: "switcher",
    label: "ATEM Constellation 2 M/E",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM 2 M/E Constellation HD",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemconstellation",
    searchTerms: ["blackmagic", "atem", "constellation", "2me"],
    ports: [
      ...ports("SDI In", "sdi", "input", 20),
      ...ports("SDI Out", "sdi", "output", 12),
      port("Ref In", "genlock", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Analog In L", "analog-audio", "input", "trs-quarter"),
    
      port("Analog In R", "analog-audio", "input", "trs-quarter"),
    
      port("Talkback", "analog-audio", "bidirectional", "xlr-5"),
    
      port("MADI", "madi", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0048-4000-8000-000000000072",
    deviceType: "switcher",
    label: "ATEM Constellation 4 M/E",
    manufacturer: "Blackmagic Design",
    modelNumber: "ATEM 4 M/E Constellation HD",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemconstellation",
    searchTerms: ["blackmagic", "atem", "constellation", "4me"],
    ports: [
      ...ports("SDI In", "sdi", "input", 40),
      ...ports("SDI Out", "sdi", "output", 24),
      port("Ref In", "genlock", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Analog In L", "analog-audio", "input", "trs-quarter"),
    
      port("Analog In R", "analog-audio", "input", "trs-quarter"),
    
      port("MADI In", "madi", "input"),
    
      port("MADI Out 1", "madi", "output"),
    
      port("MADI Out 2", "madi", "output"),
    
      port("Talkback", "analog-audio", "bidirectional", "xlr-5"),
    
      port("RS-422", "rs422", "bidirectional", "rj45"),
    
      port("Analog Out L", "analog-audio", "output", "trs-quarter"),
    
      port("Analog Out R", "analog-audio", "output", "trs-quarter"),
    ],
  },
  {
    id: "c0a80101-0049-4000-8000-000000000073",
    deviceType: "switcher",
    label: "Roland V-60HD",
    manufacturer: "Roland",
    modelNumber: "V-60HD",
    referenceUrl: "https://proav.roland.com/global/products/v-60hd/",
    searchTerms: ["roland", "v60hd", "multi-format", "switcher"],
    ports: [
      ...ports("HDMI In", "hdmi", "input", 4),
      ...ports("SDI In", "sdi", "input", 4),
      port("HDMI PGM", "hdmi", "output"),
      port("HDMI PVW", "hdmi", "output"),
      port("HDMI MV", "hdmi", "output"),
      port("SDI PGM", "sdi", "output"),
      port("SDI PVW", "sdi", "output"),
      port("USB-C Out", "usb", "output", "usb-c"),
      port("XLR In 1", "analog-audio", "input"),
      port("XLR In 2", "analog-audio", "input"),
      port("XLR Out 1", "analog-audio", "output"),
      port("XLR Out 2", "analog-audio", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("HDMI In 5", "hdmi", "input"),
    
      port("HDMI In 6", "hdmi", "input"),
    
      port("VGA In", "vga", "input"),
    
      port("XLR In 3", "analog-audio", "input"),
    
      port("XLR In 4", "analog-audio", "input"),
    
      port("RCA In 5", "analog-audio", "input", "rca"),
    
      port("RCA In 6", "analog-audio", "input", "rca"),
    
      port("RCA Out", "analog-audio", "output", "rca"),
    ],
  },
  {
    id: "c0a80101-004a-4000-8000-000000000074",
    deviceType: "switcher",
    label: "Barco E2 Gen 2",
    manufacturer: "Barco",
    modelNumber: "E2 Gen 2",
    referenceUrl: "https://www.barco.com/en/product/e2-gen-2",
    searchTerms: ["barco", "e2", "event master", "presentation"],
    slots: [
      { id: "e2-in-1", label: "Input Slot 1", slotFamily: "barco-em-input" },
      { id: "e2-in-2", label: "Input Slot 2", slotFamily: "barco-em-input" },
      { id: "e2-in-3", label: "Input Slot 3", slotFamily: "barco-em-input" },
      { id: "e2-in-4", label: "Input Slot 4", slotFamily: "barco-em-input" },
      { id: "e2-in-5", label: "Input Slot 5", slotFamily: "barco-em-input" },
      { id: "e2-in-6", label: "Input Slot 6", slotFamily: "barco-em-input" },
      { id: "e2-in-7", label: "Input Slot 7", slotFamily: "barco-em-input" },
      { id: "e2-in-8", label: "Input Slot 8", slotFamily: "barco-em-input" },
      { id: "e2-out-1", label: "Output Slot 1", slotFamily: "barco-em-output" },
      { id: "e2-out-2", label: "Output Slot 2", slotFamily: "barco-em-output" },
      { id: "e2-out-3", label: "Output Slot 3", slotFamily: "barco-em-output" },
      { id: "e2-out-4", label: "Output Slot 4", slotFamily: "barco-em-output" },
    ],
    ports: [
      port("Ref In", "genlock", "input"),
      port("Ref Loop Out", "genlock", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-004b-4000-8000-000000000075",
    deviceType: "switcher",
    label: "Barco S3-4K",
    manufacturer: "Barco",
    modelNumber: "S3-4K",
    referenceUrl: "https://www.barco.com/en/product/s3-4k",
    searchTerms: ["barco", "s3", "event master", "4k", "presentation"],
    slots: [
      { id: "s3-in-1", label: "Input Slot 1", slotFamily: "barco-em-input" },
      { id: "s3-in-2", label: "Input Slot 2", slotFamily: "barco-em-input" },
      { id: "s3-in-3", label: "Input Slot 3", slotFamily: "barco-em-input" },
      { id: "s3-in-4", label: "Input Slot 4", slotFamily: "barco-em-input" },
      { id: "s3-out-1", label: "Output Slot 1", slotFamily: "barco-em-output" },
      { id: "s3-out-2", label: "Output Slot 2", slotFamily: "barco-em-output" },
      { id: "s3-out-3", label: "Output Slot 3", slotFamily: "barco-em-output" },
      { id: "s3-mvr-1", label: "MVR/Output Slot", slotFamily: "barco-em-output" },
    ],
    ports: [
      port("Ref In", "genlock", "input"),
      port("Ref Loop Out", "genlock", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-004c-4000-8000-000000000076",
    deviceType: "switcher",
    label: "Analog Way Aquilon C",
    manufacturer: "Analog Way",
    modelNumber: "Aquilon C",
    referenceUrl: "https://www.analogway.com/emea/products/midra-range/aquilon-c/",
    searchTerms: ["analog way", "aquilon", "presentation", "4k"],
    slots: [
      { id: "aql-in-1", label: "Input Slot 1", slotFamily: "aw-aql-input" },
      { id: "aql-in-2", label: "Input Slot 2", slotFamily: "aw-aql-input" },
      { id: "aql-in-3", label: "Input Slot 3", slotFamily: "aw-aql-input" },
      { id: "aql-in-4", label: "Input Slot 4", slotFamily: "aw-aql-input" },
      { id: "aql-out-1", label: "Output Slot 1", slotFamily: "aw-aql-output" },
      { id: "aql-out-2", label: "Output Slot 2", slotFamily: "aw-aql-output" },
      { id: "aql-out-3", label: "Output Slot 3", slotFamily: "aw-aql-output" },
      { id: "aql-out-4", label: "Output Slot 4", slotFamily: "aw-aql-output" },
    ],
    ports: [
      port("Dante", "dante", "bidirectional"),
      port("Ref In", "genlock", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Video Routers ────────────────────────────────────────────────
  {
    id: "c0a80101-004d-4000-8000-000000000077",
    deviceType: "router",
    label: "BMD Videohub 12G 10x10",
    manufacturer: "Blackmagic Design",
    modelNumber: "Smart Videohub 12G 10x10",
    referenceUrl: "https://www.blackmagicdesign.com/products/smartvideohub",
    searchTerms: ["blackmagic", "videohub", "12g", "10x10"],
    ports: [
      ...ports("In", "sdi", "input", 10),
      ...ports("Out", "sdi", "output", 10),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Ref In", "genlock", "input"),
    ],
  },
  {
    id: "c0a80101-004e-4000-8000-000000000078",
    deviceType: "router",
    label: "BMD Videohub 12G 40x40",
    manufacturer: "Blackmagic Design",
    modelNumber: "Smart Videohub 12G 40x40",
    referenceUrl: "https://www.blackmagicdesign.com/products/smartvideohub",
    searchTerms: ["blackmagic", "videohub", "12g", "40x40"],
    ports: [
      ...ports("In", "sdi", "input", 40),
      ...ports("Out", "sdi", "output", 40),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Ref In", "genlock", "input"),
    ],
  },
  {
    id: "c0a80101-004f-4000-8000-000000000079",
    deviceType: "router",
    label: "BMD Videohub 80x80 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Universal Videohub 72",
    referenceUrl: "https://www.blackmagicdesign.com/products/blackmagicvideohub",
    searchTerms: ["blackmagic", "videohub", "universal", "72x72", "matrix"],
    ports: [
      ...ports("In", "sdi", "input", 72),
      ...ports("Out", "sdi", "output", 72),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("Ref In", "genlock", "input"),
    ],
  },
  {
    id: "c0a80101-0050-4000-8000-000000000080",
    deviceType: "router",
    label: "Lightware MX2 8x8 HDMI",
    manufacturer: "Lightware",
    modelNumber: "MX2-8x8-HDMI20",
    referenceUrl: "https://lightware.com/mx2-8x8-hdmi20",
    searchTerms: ["lightware", "mx2", "hdmi", "8x8", "matrix"],
    ports: [
      ...ports("HDMI In", "hdmi", "input", 8),
      ...ports("HDMI Out", "hdmi", "output", 8),
      port("Ethernet", "ethernet", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0051-4000-8000-000000000081",
    deviceType: "router",
    label: "Lightware MX2 16x16 HDMI",
    manufacturer: "Lightware",
    modelNumber: "MX2-16x16-HDMI20",
    referenceUrl: "https://lightware.com/mx2-16x16-hdmi20",
    searchTerms: ["lightware", "mx2", "hdmi", "16x16", "matrix"],
    ports: [
      ...ports("HDMI In", "hdmi", "input", 16),
      ...ports("HDMI Out", "hdmi", "output", 16),
      port("Ethernet", "ethernet", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0103-4000-8000-000000000335",
    deviceType: "router",
    category: "routing",
    label: "AJA KUMO 1616-12G",
    manufacturer: "AJA",
    modelNumber: "KUMO 1616-12G",
    referenceUrl: "https://www.aja.com/products/kumo-1616-12g",
    searchTerms: ["aja", "kumo", "router", "16x16", "12g", "sdi"],
    ports: [
      ...ports("In", "sdi", "input", 16),
      ...ports("Out", "sdi", "output", 16),
      port("Ref In", "genlock", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Modular Routers ─────────────────────────────────────────────
  {
    id: "c0a80101-0115-4000-8000-000000000353",
    deviceType: "router",
    label: "Crestron DM-MD8X8-CPU3",
    manufacturer: "Crestron",
    modelNumber: "DM-MD8X8-CPU3",
    referenceUrl: "https://www.crestron.com/Products/Video/DigitalMedia-Modular-Matrix/Switcher-Chassis/DM-MD8X8-CPU3",
    searchTerms: ["crestron", "dm", "md8x8", "modular", "matrix", "8x8"],
    slots: [
      { id: "dm8-in-1", label: "Input Slot 1", slotFamily: "crestron-dm-input" },
      { id: "dm8-in-2", label: "Input Slot 2", slotFamily: "crestron-dm-input" },
      { id: "dm8-in-3", label: "Input Slot 3", slotFamily: "crestron-dm-input" },
      { id: "dm8-in-4", label: "Input Slot 4", slotFamily: "crestron-dm-input" },
      { id: "dm8-in-5", label: "Input Slot 5", slotFamily: "crestron-dm-input" },
      { id: "dm8-in-6", label: "Input Slot 6", slotFamily: "crestron-dm-input" },
      { id: "dm8-in-7", label: "Input Slot 7", slotFamily: "crestron-dm-input" },
      { id: "dm8-in-8", label: "Input Slot 8", slotFamily: "crestron-dm-input" },
      { id: "dm8-out-1", label: "Output Slot 1", slotFamily: "crestron-dm-output" },
      { id: "dm8-out-2", label: "Output Slot 2", slotFamily: "crestron-dm-output" },
      { id: "dm8-out-3", label: "Output Slot 3", slotFamily: "crestron-dm-output" },
      { id: "dm8-out-4", label: "Output Slot 4", slotFamily: "crestron-dm-output" },
    ],
    ports: [
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0116-4000-8000-000000000354",
    deviceType: "router",
    label: "Crestron DM-MD16X16-CPU3",
    manufacturer: "Crestron",
    modelNumber: "DM-MD16X16-CPU3",
    referenceUrl: "https://www.crestron.com/Products/Video/DigitalMedia-Modular-Matrix/Switcher-Chassis/DM-MD16X16-CPU3",
    searchTerms: ["crestron", "dm", "md16x16", "modular", "matrix", "16x16"],
    slots: [
      { id: "dm16-in-1", label: "Input Slot 1", slotFamily: "crestron-dm-input" },
      { id: "dm16-in-2", label: "Input Slot 2", slotFamily: "crestron-dm-input" },
      { id: "dm16-in-3", label: "Input Slot 3", slotFamily: "crestron-dm-input" },
      { id: "dm16-in-4", label: "Input Slot 4", slotFamily: "crestron-dm-input" },
      { id: "dm16-in-5", label: "Input Slot 5", slotFamily: "crestron-dm-input" },
      { id: "dm16-in-6", label: "Input Slot 6", slotFamily: "crestron-dm-input" },
      { id: "dm16-in-7", label: "Input Slot 7", slotFamily: "crestron-dm-input" },
      { id: "dm16-in-8", label: "Input Slot 8", slotFamily: "crestron-dm-input" },
      { id: "dm16-out-1", label: "Output Slot 1", slotFamily: "crestron-dm-output" },
      { id: "dm16-out-2", label: "Output Slot 2", slotFamily: "crestron-dm-output" },
      { id: "dm16-out-3", label: "Output Slot 3", slotFamily: "crestron-dm-output" },
      { id: "dm16-out-4", label: "Output Slot 4", slotFamily: "crestron-dm-output" },
      { id: "dm16-out-5", label: "Output Slot 5", slotFamily: "crestron-dm-output" },
      { id: "dm16-out-6", label: "Output Slot 6", slotFamily: "crestron-dm-output" },
      { id: "dm16-out-7", label: "Output Slot 7", slotFamily: "crestron-dm-output" },
      { id: "dm16-out-8", label: "Output Slot 8", slotFamily: "crestron-dm-output" },
    ],
    ports: [
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0117-4000-8000-000000000355",
    deviceType: "router",
    label: "Lightware MX2M-FR24R",
    manufacturer: "Lightware",
    modelNumber: "MX2M-FR24R",
    referenceUrl: "https://lightware.com/mx2m-fr24r-rf",
    searchTerms: ["lightware", "mx2m", "fr24r", "modular", "matrix", "24x24"],
    slots: [
      { id: "mx2m-in-1", label: "Video Input Slot 1", slotFamily: "lightware-mx2m-video-in" },
      { id: "mx2m-in-2", label: "Video Input Slot 2", slotFamily: "lightware-mx2m-video-in" },
      { id: "mx2m-in-3", label: "Video Input Slot 3", slotFamily: "lightware-mx2m-video-in" },
      { id: "mx2m-in-4", label: "Video Input Slot 4", slotFamily: "lightware-mx2m-video-in" },
      { id: "mx2m-in-5", label: "Video Input Slot 5", slotFamily: "lightware-mx2m-video-in" },
      { id: "mx2m-in-6", label: "Video Input Slot 6", slotFamily: "lightware-mx2m-video-in" },
      { id: "mx2m-out-1", label: "Video Output Slot 1", slotFamily: "lightware-mx2m-video-out" },
      { id: "mx2m-out-2", label: "Video Output Slot 2", slotFamily: "lightware-mx2m-video-out" },
      { id: "mx2m-out-3", label: "Video Output Slot 3", slotFamily: "lightware-mx2m-video-out" },
      { id: "mx2m-out-4", label: "Video Output Slot 4", slotFamily: "lightware-mx2m-video-out" },
      { id: "mx2m-out-5", label: "Video Output Slot 5", slotFamily: "lightware-mx2m-video-out" },
      { id: "mx2m-out-6", label: "Video Output Slot 6", slotFamily: "lightware-mx2m-video-out" },
    ],
    ports: [
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Fixed-Port Routers ──────────────────────────────────────────
  {
    id: "c0a80101-0118-4000-8000-000000000356",
    deviceType: "router",
    label: "Extron DTP CrossPoint 84 4K",
    manufacturer: "Extron",
    modelNumber: "DTP CrossPoint 84 4K",
    referenceUrl: "https://www.extron.com/product/dtpcp4k84",
    searchTerms: ["extron", "dtp", "crosspoint", "84", "4k", "matrix"],
    ports: [
      ...ports("HDMI In", "hdmi", "input", 6),
      ...ports("HDBaseT In", "hdbaset", "input", 2),
      ...ports("HDMI Out", "hdmi", "output", 2),
      ...ports("HDBaseT Out", "hdbaset", "output", 2),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0119-4000-8000-000000000357",
    deviceType: "router",
    label: "Extron DTP CrossPoint 108 4K",
    manufacturer: "Extron",
    modelNumber: "DTP CrossPoint 108 4K",
    referenceUrl: "https://www.extron.com/product/dtpcp4k108",
    searchTerms: ["extron", "dtp", "crosspoint", "108", "4k", "matrix"],
    ports: [
      ...ports("HDMI In", "hdmi", "input", 6),
      ...ports("HDBaseT In", "hdbaset", "input", 4),
      ...ports("HDMI Out", "hdmi", "output", 4),
      ...ports("HDBaseT Out", "hdbaset", "output", 4),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
];
