# build stage
FROM node:lts-bookworm AS builder

# install dependencies
RUN npm install -g npm@latest
RUN apt install git && git clone https://github.com/duremovich/EasySchematic.git
WORKDIR /EasySchematic

RUN npm install
RUN npm run build


# production stage
FROM nginx:bookworm

COPY --from=builder /EasySchematic/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]