import type { ConnectorType, DeviceTemplate, Port } from "./types";
import { DEFAULT_CONNECTOR } from "./connectorTypes";

let portIdCounter = 0;
function port(
  label: string,
  signalType: Port["signalType"],
  direction: Port["direction"],
  connectorType?: ConnectorType,
): Port {
  return {
    id: `port-${++portIdCounter}`,
    label,
    signalType,
    direction,
    connectorType: connectorType ?? DEFAULT_CONNECTOR[signalType],
  };
}

export const DEVICE_TEMPLATES: DeviceTemplate[] = [
  // Cameras
  {
    id: "c0a80101-0001-4000-8000-000000000001",
    deviceType: "camera",
    label: "Camera",
    ports: [
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("Genlock In", "genlock", "input"),
      port("Return In", "sdi", "input"),
      port("AC Power", "power", "input"),
    ],
  },
  // Switchers
  {
    id: "c0a80101-0002-4000-8000-000000000002",
    deviceType: "switcher",
    label: "Video Switcher",
    ports: [
      port("SDI In 1", "sdi", "input"),
      port("SDI In 2", "sdi", "input"),
      port("SDI In 3", "sdi", "input"),
      port("SDI In 4", "sdi", "input"),
      port("PGM Out", "sdi", "output"),
      port("PVW Out", "sdi", "output"),
      port("AUX Out", "sdi", "output"),
      port("Multiview", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Monitors
  {
    id: "c0a80101-0003-4000-8000-000000000003",
    deviceType: "monitor",
    label: "Monitor",
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Loop", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // TV
  {
    id: "c0a80101-0004-4000-8000-000000000004",
    deviceType: "tv",
    label: "TV",
    searchTerms: ["television", "display", "screen"],
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("AC Power", "power", "input"),
    ],
  },
  // Audio Mixer
  {
    id: "c0a80101-0005-4000-8000-000000000005",
    deviceType: "audio-mixer",
    label: "Audio Mixer",
    ports: [
      port("Analog In 1", "analog-audio", "input"),
      port("Analog In 2", "analog-audio", "input"),
      port("Dante In", "dante", "input"),
      port("AES In", "aes", "input"),
      port("PGM Out", "analog-audio", "output"),
      port("AUX Out", "analog-audio", "output"),
      port("Dante Out", "dante", "output"),
      port("AES Out", "aes", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Blackmagic Micro Converter SDI to HDMI
  {
    id: "c0a80101-0006-4000-8000-000000000006",
    deviceType: "converter",
    label: "BMD SDI→HDMI",
    manufacturer: "Blackmagic Design",
    modelNumber: "Micro Converter SDI to HDMI 3G",
    referenceUrl: "https://www.blackmagicdesign.com/products/microconverters/techspecs/W-CONU-12",
    searchTerms: ["blackmagic", "micro converter", "microconverter"],
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI Out", "hdmi", "output"),
      port("SDI Loop", "sdi", "output"),
    ],
  },
  // Blackmagic Micro Converter HDMI to SDI
  {
    id: "c0a80101-0007-4000-8000-000000000007",
    deviceType: "converter",
    label: "BMD HDMI→SDI",
    manufacturer: "Blackmagic Design",
    modelNumber: "Micro Converter HDMI to SDI 3G",
    referenceUrl: "https://www.blackmagicdesign.com/products/microconverters/techspecs/W-CONU-11",
    searchTerms: ["blackmagic", "micro converter", "microconverter"],
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("SDI Out", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
    ],
  },
  // Decimator MD-LX — Bidirectional SDI/HDMI Cross Converter
  {
    id: "c0a80101-0008-4000-8000-000000000008",
    deviceType: "converter",
    label: "Decimator MD-LX",
    manufacturer: "Decimator Design",
    modelNumber: "MD-LX",
    referenceUrl: "https://decimator.com/Products/MiniConverters/MD-LX/MD-LX.html",
    searchTerms: ["decimator", "cross converter", "bidirectional"],
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Out", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  // Blackmagic Micro Converter BiDirectional SDI/HDMI 3G
  {
    id: "c0a80101-0009-4000-8000-000000000009",
    deviceType: "converter",
    label: "BMD BiDir SDI/HDMI 3G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Micro Converter BiDirectional SDI/HDMI 3G",
    referenceUrl: "https://www.blackmagicdesign.com/products/microconverters/techspecs/W-CONU-09",
    searchTerms: ["blackmagic", "micro converter", "bidirectional", "3g"],
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Out", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  // AJA FiDO-4T — Quad SDI to Fiber Transmitter
  {
    id: "c0a80101-000a-4000-8000-000000000010",
    deviceType: "converter",
    label: "AJA FiDO-4T",
    manufacturer: "AJA",
    modelNumber: "FiDO-4T",
    referenceUrl: "https://www.aja.com/products/fido-4t",
    searchTerms: ["aja", "fido", "fiber", "transmitter", "quad"],
    ports: [
      port("SDI In 1", "sdi", "input"),
      port("SDI In 2", "sdi", "input"),
      port("SDI In 3", "sdi", "input"),
      port("SDI In 4", "sdi", "input"),
      port("Fiber Out 1", "fiber", "output"),
      port("Fiber Out 2", "fiber", "output"),
      port("Fiber Out 3", "fiber", "output"),
      port("Fiber Out 4", "fiber", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // AJA FiDO-4R — Quad Fiber to SDI Receiver
  {
    id: "c0a80101-000b-4000-8000-000000000011",
    deviceType: "converter",
    label: "AJA FiDO-4R",
    manufacturer: "AJA",
    modelNumber: "FiDO-4R",
    referenceUrl: "https://www.aja.com/products/fido-4r",
    searchTerms: ["aja", "fido", "fiber", "receiver", "quad"],
    ports: [
      port("Fiber In 1", "fiber", "input"),
      port("Fiber In 2", "fiber", "input"),
      port("Fiber In 3", "fiber", "input"),
      port("Fiber In 4", "fiber", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("SDI Out 3", "sdi", "output"),
      port("SDI Out 4", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // AJA FiDO-T — Single SDI to Fiber Transmitter
  {
    id: "c0a80101-000c-4000-8000-000000000012",
    deviceType: "converter",
    label: "AJA FiDO-T",
    manufacturer: "AJA",
    modelNumber: "FiDO-T",
    referenceUrl: "https://www.aja.com/products/fido-t",
    searchTerms: ["aja", "fido", "fiber", "transmitter", "single"],
    ports: [
      port("SDI In", "sdi", "input"),
      port("Fiber Out", "fiber", "output"),
      port("SDI Loop", "sdi", "output"),
    ],
  },
  // AJA FiDO-R — Single Fiber to SDI Receiver
  {
    id: "c0a80101-000d-4000-8000-000000000013",
    deviceType: "converter",
    label: "AJA FiDO-R",
    manufacturer: "AJA",
    modelNumber: "FiDO-R",
    referenceUrl: "https://www.aja.com/products/fido-r",
    searchTerms: ["aja", "fido", "fiber", "receiver", "single"],
    ports: [
      port("Fiber In", "fiber", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
    ],
  },
  // Datavideo DAC-70 — Cross Converter
  {
    id: "c0a80101-000e-4000-8000-000000000014",
    deviceType: "converter",
    label: "Datavideo DAC-70",
    manufacturer: "Datavideo",
    modelNumber: "DAC-70",
    referenceUrl: "https://www.datavideo.com/us/product/DAC-70",
    searchTerms: ["datavideo", "cross converter", "dac", "vga"],
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("VGA In", "vga", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("SDI Loop", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Decimator MD-HX — Scaler / Cross Converter
  {
    id: "c0a80101-000f-4000-8000-000000000015",
    deviceType: "scaler",
    label: "Decimator MD-HX",
    manufacturer: "Decimator Design",
    modelNumber: "MD-HX",
    referenceUrl: "https://decimator.com/Products/MiniConverters/MD-HX/MD-HX.html",
    searchTerms: ["decimator", "cross converter", "scaler", "upconverter", "downconverter"],
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  // Extron DSC 301 HD — Presentation Scaler
  {
    id: "c0a80101-0010-4000-8000-000000000016",
    deviceType: "scaler",
    label: "Extron DSC 301 HD",
    manufacturer: "Extron",
    modelNumber: "DSC 301 HD",
    referenceUrl: "https://www.extron.com/product/dsc301hd",
    searchTerms: ["extron", "presentation scaler", "vga", "scan converter"],
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("VGA In", "vga", "input"),
      port("Composite In", "composite", "input"),
      port("Audio In 1", "analog-audio", "input"),
      port("Audio In 2", "analog-audio", "input"),
      port("Audio In 3", "analog-audio", "input"),
      port("HDMI Out", "hdmi", "output"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Converter
  {
    id: "c0a80101-0011-4000-8000-000000000017",
    deviceType: "converter",
    label: "Converter",
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  // NDI Encoder
  {
    id: "c0a80101-0012-4000-8000-000000000018",
    deviceType: "ndi-encoder",
    label: "NDI Encoder",
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("NDI Out", "ndi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // NDI Decoder
  {
    id: "c0a80101-0013-4000-8000-000000000019",
    deviceType: "ndi-decoder",
    label: "NDI Decoder",
    ports: [
      port("NDI In", "ndi", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("SDI Out", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Router
  {
    id: "c0a80101-0014-4000-8000-000000000020",
    deviceType: "router",
    label: "SDI Router",
    ports: [
      port("In 1", "sdi", "input"),
      port("In 2", "sdi", "input"),
      port("In 3", "sdi", "input"),
      port("In 4", "sdi", "input"),
      port("Out 1", "sdi", "output"),
      port("Out 2", "sdi", "output"),
      port("Out 3", "sdi", "output"),
      port("Out 4", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Blackmagic Smart Videohub 20x20
  {
    id: "c0a80101-0015-4000-8000-000000000021",
    deviceType: "router",
    label: "BMD Videohub 20x20",
    manufacturer: "Blackmagic Design",
    modelNumber: "Smart Videohub 20x20",
    referenceUrl: "https://www.blackmagicdesign.com/products/blackmagicvideohub/techspecs",
    searchTerms: ["blackmagic", "smart videohub", "videohub", "20x20", "matrix"],
    ports: [
      port("In 1", "sdi", "input"),
      port("In 2", "sdi", "input"),
      port("In 3", "sdi", "input"),
      port("In 4", "sdi", "input"),
      port("In 5", "sdi", "input"),
      port("In 6", "sdi", "input"),
      port("In 7", "sdi", "input"),
      port("In 8", "sdi", "input"),
      port("In 9", "sdi", "input"),
      port("In 10", "sdi", "input"),
      port("In 11", "sdi", "input"),
      port("In 12", "sdi", "input"),
      port("In 13", "sdi", "input"),
      port("In 14", "sdi", "input"),
      port("In 15", "sdi", "input"),
      port("In 16", "sdi", "input"),
      port("In 17", "sdi", "input"),
      port("In 18", "sdi", "input"),
      port("In 19", "sdi", "input"),
      port("In 20", "sdi", "input"),
      port("Out 1", "sdi", "output"),
      port("Out 2", "sdi", "output"),
      port("Out 3", "sdi", "output"),
      port("Out 4", "sdi", "output"),
      port("Out 5", "sdi", "output"),
      port("Out 6", "sdi", "output"),
      port("Out 7", "sdi", "output"),
      port("Out 8", "sdi", "output"),
      port("Out 9", "sdi", "output"),
      port("Out 10", "sdi", "output"),
      port("Out 11", "sdi", "output"),
      port("Out 12", "sdi", "output"),
      port("Out 13", "sdi", "output"),
      port("Out 14", "sdi", "output"),
      port("Out 15", "sdi", "output"),
      port("Out 16", "sdi", "output"),
      port("Out 17", "sdi", "output"),
      port("Out 18", "sdi", "output"),
      port("Out 19", "sdi", "output"),
      port("Out 20", "sdi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Blackmagic CleanSwitch 12x12
  {
    id: "c0a80101-0016-4000-8000-000000000022",
    deviceType: "router",
    label: "BMD CleanSwitch 12x12",
    manufacturer: "Blackmagic Design",
    modelNumber: "CleanSwitch 12x12",
    referenceUrl: "https://www.blackmagicdesign.com/products/blackmagicvideohub/techspecs/W-VHS-06",
    searchTerms: ["blackmagic", "videohub", "cleanswitch", "clean switch", "12x12"],
    ports: [
      port("In 1", "sdi", "input"),
      port("In 2", "sdi", "input"),
      port("In 3", "sdi", "input"),
      port("In 4", "sdi", "input"),
      port("In 5", "sdi", "input"),
      port("In 6", "sdi", "input"),
      port("In 7", "sdi", "input"),
      port("In 8", "sdi", "input"),
      port("In 9", "sdi", "input"),
      port("In 10", "sdi", "input"),
      port("In 11", "sdi", "input"),
      port("In 12", "sdi", "input"),
      port("Out 1", "sdi", "output"),
      port("Out 2", "sdi", "output"),
      port("Out 3", "sdi", "output"),
      port("Out 4", "sdi", "output"),
      port("Out 5", "sdi", "output"),
      port("Out 6", "sdi", "output"),
      port("Out 7", "sdi", "output"),
      port("Out 8", "sdi", "output"),
      port("Out 9", "sdi", "output"),
      port("Out 10", "sdi", "output"),
      port("Out 11", "sdi", "output"),
      port("Out 12", "sdi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Kramer VS-88H2 — 8x8 HDMI Matrix Switcher
  {
    id: "c0a80101-0017-4000-8000-000000000023",
    deviceType: "router",
    label: "Kramer VS-88H2",
    manufacturer: "Kramer",
    modelNumber: "VS-88H2",
    referenceUrl: "https://www1.kramerav.com/us/product/vs-88h2",
    searchTerms: ["kramer", "hdmi", "matrix", "8x8", "switcher"],
    ports: [
      port("HDMI In 1", "hdmi", "input"),
      port("HDMI In 2", "hdmi", "input"),
      port("HDMI In 3", "hdmi", "input"),
      port("HDMI In 4", "hdmi", "input"),
      port("HDMI In 5", "hdmi", "input"),
      port("HDMI In 6", "hdmi", "input"),
      port("HDMI In 7", "hdmi", "input"),
      port("HDMI In 8", "hdmi", "input"),
      port("HDMI Out 1", "hdmi", "output"),
      port("HDMI Out 2", "hdmi", "output"),
      port("HDMI Out 3", "hdmi", "output"),
      port("HDMI Out 4", "hdmi", "output"),
      port("HDMI Out 5", "hdmi", "output"),
      port("HDMI Out 6", "hdmi", "output"),
      port("HDMI Out 7", "hdmi", "output"),
      port("HDMI Out 8", "hdmi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Multiviewer
  {
    id: "c0a80101-0018-4000-8000-000000000024",
    deviceType: "multiviewer",
    label: "Multiviewer",
    ports: [
      port("SDI In 1", "sdi", "input"),
      port("SDI In 2", "sdi", "input"),
      port("SDI In 3", "sdi", "input"),
      port("SDI In 4", "sdi", "input"),
      port("HDMI Out", "hdmi", "output"),
      port("SDI Out", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Frame Sync
  {
    id: "c0a80101-0019-4000-8000-000000000025",
    deviceType: "frame-sync",
    label: "Frame Sync",
    ports: [
      port("SDI In", "sdi", "input"),
      port("Ref In", "genlock", "input"),
      port("SDI Out", "sdi", "output"),
    ],
  },
  // Recorder
  {
    id: "c0a80101-001a-4000-8000-000000000026",
    deviceType: "recorder",
    label: "Recorder",
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Out", "sdi", "output"),
    ],
  },
  // Blackmagic HyperDeck Extreme
  {
    id: "c0a80101-001b-4000-8000-000000000027",
    deviceType: "recorder",
    label: "BMD HyperDeck Extreme",
    manufacturer: "Blackmagic Design",
    modelNumber: "HyperDeck Extreme 8K HDR",
    referenceUrl: "https://www.blackmagicdesign.com/products/hyperdeckextreme/techspecs",
    searchTerms: ["blackmagic", "hyperdeck", "4k", "hdr", "recorder", "player"],
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Out", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("SDI Monitor", "sdi", "output"),
      port("RS-422", "rs422", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Graphics
  {
    id: "c0a80101-001c-4000-8000-000000000028",
    deviceType: "graphics",
    label: "Graphics Generator",
    ports: [
      port("SDI Fill", "sdi", "output"),
      port("SDI Key", "sdi", "output"),
      port("NDI Out", "ndi", "output"),
    ],
  },
  // Distribution Amp
  {
    id: "c0a80101-001d-4000-8000-000000000029",
    deviceType: "da",
    label: "Distribution Amp",
    ports: [
      port("SDI In", "sdi", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("SDI Out 3", "sdi", "output"),
      port("SDI Out 4", "sdi", "output"),
    ],
  },
  // Thunderbolt to HDMI Adapter
  {
    id: "c0a80101-001e-4000-8000-000000000030",
    deviceType: "adapter",
    label: "TB → HDMI Adapter",
    searchTerms: ["thunderbolt", "usb-c", "dongle"],
    ports: [
      port("TB In", "thunderbolt", "input"),
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  // Blackmagic UltraStudio 4K Mini
  {
    id: "c0a80101-001f-4000-8000-000000000031",
    deviceType: "adapter",
    label: "BMD UltraStudio 4K Mini",
    manufacturer: "Blackmagic Design",
    modelNumber: "UltraStudio 4K Mini",
    referenceUrl: "https://www.blackmagicdesign.com/products/ultrastudio/techspecs/W-DLUS-11",
    searchTerms: ["blackmagic", "ultrastudio", "capture", "playback", "thunderbolt"],
    ports: [
      port("SDI In 1", "sdi", "input"),
      port("SDI In 2", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("Thunderbolt 3", "thunderbolt", "bidirectional"),
      port("RS-422", "rs422", "bidirectional"),
    ],
  },
  // Datapath FX4 SDI — Video Wall Controller (SDI variant)
  {
    id: "c0a80101-0020-4000-8000-000000000032",
    deviceType: "video-wall-controller",
    label: "Datapath FX4 SDI",
    manufacturer: "Datapath",
    modelNumber: "FX4 SDI",
    referenceUrl: "https://www.datapath.co.uk/datapath-products/video-wall-controllers/datapath-fx4-sdi/",
    searchTerms: ["datapath", "video wall"],
    ports: [
      port("SDI In", "sdi", "input"),
      port("DP In", "displayport", "input"),
      port("HDMI In", "hdmi", "input"),
      port("Genlock In", "genlock", "input"),
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("SDI Out 3", "sdi", "output"),
      port("SDI Out 4", "sdi", "output"),
      port("DP Loop", "displayport", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Datapath FX4 HDMI — Video Wall Controller
  {
    id: "c0a80101-0021-4000-8000-000000000033",
    deviceType: "video-wall-controller",
    label: "Datapath FX4 HDMI",
    manufacturer: "Datapath",
    modelNumber: "FX4 HDMI",
    referenceUrl: "https://www.datapath.co.uk/datapath-products/video-wall-controllers/datapath-fx4/",
    ports: [
      port("DP In", "displayport", "input"),
      port("HDMI In 1", "hdmi", "input"),
      port("HDMI In 2", "hdmi", "input"),
      port("Genlock In", "genlock", "input"),
      port("HDMI Out 1", "hdmi", "output"),
      port("HDMI Out 2", "hdmi", "output"),
      port("HDMI Out 3", "hdmi", "output"),
      port("HDMI Out 4", "hdmi", "output"),
      port("DP Loop", "displayport", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Panasonic PT-DZ13K — Large Venue Projector
  {
    id: "c0a80101-0022-4000-8000-000000000034",
    deviceType: "projector",
    label: "Panasonic DZ13K",
    manufacturer: "Panasonic",
    modelNumber: "PT-DZ13K",
    referenceUrl: "https://na.panasonic.com/us/audio-video-solutions/projectors/large-venue/pt-dz13ku-3-chip-dlptm-large-venue-projector",
    ports: [
      port("RGBHV In (BNC)", "vga", "input"),
      port("RGB In (VGA)", "vga", "input"),
      port("DVI-D In", "hdmi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI In 1", "sdi", "input"),
      port("SDI In 2 (3G)", "sdi", "input"),
      port("Composite In", "composite", "input"),
      port("RS-232 In", "serial", "input"),
      port("LAN", "ethernet", "bidirectional"),
      port("RS-232 Out", "serial", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Panasonic PT-RZ21K — Large Venue Laser Projector
  {
    id: "c0a80101-0023-4000-8000-000000000035",
    deviceType: "projector",
    label: "Panasonic RZ21K",
    manufacturer: "Panasonic",
    modelNumber: "PT-RZ21K",
    referenceUrl: "https://na.panasonic.com/us/audio-video-solutions/projectors/large-venue/pt-rz21ku-3-chip-dlptm-solid-shine-laser-projector",
    searchTerms: ["panasonic", "laser", "dlp", "21k", "projector"],
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("DVI-D In", "hdmi", "input"),
      port("SDI In 1", "sdi", "input"),
      port("SDI In 2", "sdi", "input"),
      port("HDBaseT In", "hdbaset", "input"),
      port("VGA In", "vga", "input"),
      port("RGB BNC In", "vga", "input"),
      port("RS-232 In", "serial", "input"),
      port("LAN", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Mac Studio (M4)
  {
    id: "c0a80101-0024-4000-8000-000000000036",
    deviceType: "computer",
    label: "Mac Studio (M4)",
    manufacturer: "Apple",
    modelNumber: "Mac Studio (M4)",
    referenceUrl: "https://www.apple.com/mac-studio/specs/",
    ports: [
      port("TB5 1", "thunderbolt", "bidirectional"),
      port("TB5 2", "thunderbolt", "bidirectional"),
      port("TB5 3", "thunderbolt", "bidirectional"),
      port("TB5 4", "thunderbolt", "bidirectional"),
      port("HDMI Out", "hdmi", "output"),
      port("USB-A 1", "usb", "bidirectional", "usb-a"),
      port("USB-A 2", "usb", "bidirectional", "usb-a"),
      port("USB-C Front 1", "usb", "bidirectional", "usb-c"),
      port("USB-C Front 2", "usb", "bidirectional", "usb-c"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Ethernet Switch (4-port)
  {
    id: "c0a80101-0025-4000-8000-000000000037",
    deviceType: "network-switch",
    label: "Ethernet Switch (4-port)",
    searchTerms: ["switch", "network", "poe"],
    ports: [
      port("Port 1", "ethernet", "bidirectional"),
      port("Port 2", "ethernet", "bidirectional"),
      port("Port 3", "ethernet", "bidirectional"),
      port("Port 4", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Ethernet Switch (8-port)
  {
    id: "c0a80101-0026-4000-8000-000000000038",
    deviceType: "network-switch",
    label: "Ethernet Switch (8-port)",
    searchTerms: ["switch", "network", "poe"],
    ports: [
      port("Port 1", "ethernet", "bidirectional"),
      port("Port 2", "ethernet", "bidirectional"),
      port("Port 3", "ethernet", "bidirectional"),
      port("Port 4", "ethernet", "bidirectional"),
      port("Port 5", "ethernet", "bidirectional"),
      port("Port 6", "ethernet", "bidirectional"),
      port("Port 7", "ethernet", "bidirectional"),
      port("Port 8", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Computer (Generic)
  {
    id: "c0a80101-0027-4000-8000-000000000039",
    deviceType: "computer",
    label: "Computer",
    searchTerms: ["pc", "laptop", "desktop"],
    ports: [
      port("HDMI Out", "hdmi", "output"),
      port("USB-C", "usb", "bidirectional", "usb-c"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Mouse
  {
    id: "c0a80101-0028-4000-8000-000000000040",
    deviceType: "mouse",
    label: "Mouse",
    searchTerms: ["mouse", "pointer", "trackpad"],
    ports: [
      port("USB-A", "usb", "bidirectional", "usb-a"),
    ],
  },
  // Keyboard
  {
    id: "c0a80101-0029-4000-8000-000000000041",
    deviceType: "keyboard",
    label: "Keyboard",
    searchTerms: ["keyboard", "keypad"],
    ports: [
      port("USB-A", "usb", "bidirectional", "usb-a"),
    ],
  },
  // PTZOptics Move SE (30x)
  {
    id: "c0a80101-002a-4000-8000-000000000042",
    deviceType: "ptz-camera",
    label: "PTZOptics Move SE",
    manufacturer: "PTZOptics",
    modelNumber: "Move SE",
    referenceUrl: "https://ptzoptics.com/move-se/",
    searchTerms: ["ptz", "ptzoptics", "pt30x", "move se"],
    ports: [
      port("3.5mm Audio In", "analog-audio", "input", "trs-eighth"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("RS-232 In", "serial", "input"),
      port("SDI Out", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("USB-C Out", "usb", "bidirectional", "usb-c"),
      port("RS-232 Out", "serial", "output"),
      port("AC Power", "power", "input"),
    ],
  },

  // KVM Extenders
  {
    id: "c0a80101-002b-4000-8000-000000000043",
    deviceType: "kvm-extender",
    label: "Adder XDIP",
    manufacturer: "Adder",
    modelNumber: "XDIP",
    referenceUrl: "https://www.adder.com/en/kvm-solutions/adderlink-xdip",
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("HDMI Out", "hdmi", "output"),
      port("USB-B (Computer)", "usb", "bidirectional", "usb-b"),
      port("USB-A 1", "usb", "bidirectional", "usb-a"),
      port("USB-A 2", "usb", "bidirectional", "usb-a"),
      port("USB-A 3", "usb", "bidirectional", "usb-a"),
      port("Audio In", "analog-audio", "input"),
      port("Audio Out", "analog-audio", "output"),
      port("Network", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
    searchTerms: ["Adder", "AdderLink", "XDIP", "KVM", "extender", "IP", "matrix"],
  },

  // HDBaseT Extenders
  // Extron DTP T HD2 4K 230 — HDBaseT Transmitter
  {
    id: "c0a80101-002c-4000-8000-000000000044",
    deviceType: "hdbaset-extender",
    label: "Extron DTP T HD2 4K",
    manufacturer: "Extron",
    modelNumber: "DTP T HD2 4K 230",
    referenceUrl: "https://www.extron.com/product/dtpthd24k230",
    searchTerms: ["extron", "dtp", "hdbaset", "transmitter", "extender"],
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("HDMI Loop", "hdmi", "output"),
      port("HDBaseT Out", "hdbaset", "output"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Extron DTP R HD2 4K 230 — HDBaseT Receiver
  {
    id: "c0a80101-002d-4000-8000-000000000045",
    deviceType: "hdbaset-extender",
    label: "Extron DTP R HD2 4K",
    manufacturer: "Extron",
    modelNumber: "DTP R HD2 4K 230",
    referenceUrl: "https://www.extron.com/product/dtphdmi230rx",
    searchTerms: ["extron", "dtp", "hdbaset", "receiver", "extender"],
    ports: [
      port("HDBaseT In", "hdbaset", "input"),
      port("HDMI Out", "hdmi", "output"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // Wireless Video
  // Teradek Bolt 4K 750 TX — Wireless Video Transmitter
  {
    id: "c0a80101-002e-4000-8000-000000000046",
    deviceType: "wireless-video",
    label: "Teradek Bolt 4K TX",
    manufacturer: "Teradek",
    modelNumber: "Bolt 4K 750 TX",
    referenceUrl: "https://teradek.com/products/bolt-4k-750-set",
    searchTerms: ["teradek", "bolt", "wireless", "transmitter", "zero delay"],
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Loop", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Teradek Bolt 4K 750 RX — Wireless Video Receiver
  {
    id: "c0a80101-002f-4000-8000-000000000047",
    deviceType: "wireless-video",
    label: "Teradek Bolt 4K RX",
    manufacturer: "Teradek",
    modelNumber: "Bolt 4K 750 RX",
    referenceUrl: "https://teradek.com/products/bolt-4k-750-rx-only",
    searchTerms: ["teradek", "bolt", "wireless", "receiver", "zero delay"],
    ports: [
      port("SDI Out 1", "sdi", "output"),
      port("SDI Out 2", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("AC Power", "power", "input"),
    ],
  },

  // Intercom
  // ClearCom FreeSpeak II Base Station
  {
    id: "c0a80101-0030-4000-8000-000000000048",
    deviceType: "intercom",
    label: "ClearCom FreeSpeak II",
    manufacturer: "Clear-Com",
    modelNumber: "FreeSpeak II Base Station",
    referenceUrl: "https://www.clearcom.com/Products/Products-By-Name/Station-IC/fsii-base-ii",
    searchTerms: ["clearcom", "clear-com", "freespeak", "wireless intercom", "base station"],
    ports: [
      port("Partyline 1", "analog-audio", "bidirectional"),
      port("Partyline 2", "analog-audio", "bidirectional"),
      port("Partyline 3", "analog-audio", "bidirectional"),
      port("Partyline 4", "analog-audio", "bidirectional"),
      port("4-Wire 1", "analog-audio", "bidirectional"),
      port("4-Wire 2", "analog-audio", "bidirectional"),
      port("Program In", "analog-audio", "input"),
      port("Stage Announce", "analog-audio", "output"),
      port("GPIO", "gpio", "bidirectional"),
      port("LAN 1", "ethernet", "bidirectional"),
      port("LAN 2", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // Audio Embedders / De-Embedders
  // BMD Teranex Mini SDI to Audio 12G — Audio De-Embedder
  {
    id: "c0a80101-0031-4000-8000-000000000049",
    deviceType: "audio-embedder",
    label: "BMD SDI→Audio 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Teranex Mini SDI to Audio 12G",
    referenceUrl: "https://www.blackmagicdesign.com/products/teranexmini/techspecs/W-TERAMIN-05",
    searchTerms: ["blackmagic", "teranex", "de-embedder", "deembed", "audio extract"],
    ports: [
      port("SDI In", "sdi", "input"),
      port("SDI Out", "sdi", "output"),
      port("Analog Out L", "analog-audio", "output"),
      port("Analog Out R", "analog-audio", "output"),
      port("AES Out 1-2", "aes", "output"),
      port("AES Out 3-4", "aes", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // BMD Teranex Mini Audio to SDI 12G — Audio Embedder
  {
    id: "c0a80101-0032-4000-8000-000000000050",
    deviceType: "audio-embedder",
    label: "BMD Audio→SDI 12G",
    manufacturer: "Blackmagic Design",
    modelNumber: "Teranex Mini Audio to SDI 12G",
    referenceUrl: "https://www.blackmagicdesign.com/products/teranexmini/techspecs/W-TERAMIN-06",
    searchTerms: ["blackmagic", "teranex", "embedder", "audio embed"],
    ports: [
      port("SDI In", "sdi", "input"),
      port("Analog In L", "analog-audio", "input"),
      port("Analog In R", "analog-audio", "input"),
      port("AES In 1-2", "aes", "input"),
      port("AES In 3-4", "aes", "input"),
      port("SDI Out", "sdi", "output"),
      port("AC Power", "power", "input"),
    ],
  },

  // Streaming Encoder
  // Teradek Prism Flex — Streaming Encoder/Decoder
  {
    id: "c0a80101-0033-4000-8000-000000000051",
    deviceType: "streaming-encoder",
    label: "Teradek Prism Flex",
    manufacturer: "Teradek",
    modelNumber: "Prism Flex",
    referenceUrl: "https://teradek.com/pages/prism-flex",
    searchTerms: ["teradek", "prism", "streaming", "encoder", "rtmp", "srt", "hevc"],
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Loop", "sdi", "output"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("USB 1", "usb", "bidirectional"),
      port("USB 2", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // Media Players
  // BrightSign XD1035 — Digital Signage Media Player
  {
    id: "c0a80101-0034-4000-8000-000000000052",
    deviceType: "media-player",
    label: "BrightSign XD1035",
    manufacturer: "BrightSign",
    modelNumber: "XD1035",
    referenceUrl: "https://docs.brightsign.biz/hardware/xd235-xd1035",
    searchTerms: ["brightsign", "digital signage", "media player", "signage"],
    ports: [
      port("HDMI Out", "hdmi", "output"),
      port("Audio Out", "analog-audio", "output", "trs-eighth"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("USB-A", "usb", "bidirectional", "usb-a"),
      port("USB-C", "usb", "bidirectional", "usb-c"),
      port("RS-232", "serial", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // Wireless Microphone Receivers
  // Shure ULXD4Q — Quad Wireless Mic Receiver
  {
    id: "c0a80101-0035-4000-8000-000000000053",
    deviceType: "wireless-mic-receiver",
    label: "Shure ULXD4Q",
    manufacturer: "Shure",
    modelNumber: "ULXD4Q",
    referenceUrl: "https://www.shure.com/en-US/products/wireless-systems/ulx-d_digital_wireless/ulxd4q",
    searchTerms: ["shure", "ulx-d", "wireless", "microphone", "receiver", "quad"],
    ports: [
      port("Analog Out 1", "analog-audio", "output"),
      port("Analog Out 2", "analog-audio", "output"),
      port("Analog Out 3", "analog-audio", "output"),
      port("Analog Out 4", "analog-audio", "output"),
      port("Dante 1", "dante", "bidirectional"),
      port("Dante 2", "dante", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Sennheiser EW-DX EM 4 Dante — Quad Wireless Mic Receiver
  {
    id: "c0a80101-0036-4000-8000-000000000054",
    deviceType: "wireless-mic-receiver",
    label: "Sennheiser EW-DX EM 4",
    manufacturer: "Sennheiser",
    modelNumber: "EW-DX EM 4 Dante",
    referenceUrl: "https://www.sennheiser.com/en-us/catalog/products/wireless-systems/ew-dx-em-4-dante/ew-dx-em-4-dante-q1-9-509370",
    searchTerms: ["sennheiser", "ew-dx", "wireless", "microphone", "receiver", "dante"],
    ports: [
      port("Analog Out 1", "analog-audio", "output"),
      port("Analog Out 2", "analog-audio", "output"),
      port("Analog Out 3", "analog-audio", "output"),
      port("Analog Out 4", "analog-audio", "output"),
      port("Dante 1", "dante", "bidirectional"),
      port("Dante 2", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // Audio Interfaces
  // Focusrite RedNet A16R MkII — Dante Audio Interface
  {
    id: "c0a80101-0037-4000-8000-000000000055",
    deviceType: "audio-interface",
    label: "Focusrite RedNet A16R",
    manufacturer: "Focusrite",
    modelNumber: "RedNet A16R MkII",
    referenceUrl: "https://us.focusrite.com/products/rednet-a16r-mkii",
    searchTerms: ["focusrite", "rednet", "dante", "audio interface", "a16r"],
    ports: [
      port("Analog In 1-8", "analog-audio", "input"),
      port("Analog In 9-16", "analog-audio", "input"),
      port("AES In", "aes", "input"),
      port("Analog Out 1-8", "analog-audio", "output"),
      port("Analog Out 9-16", "analog-audio", "output"),
      port("AES Out", "aes", "output"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Word Clock In", "genlock", "input"),
      port("Word Clock Out", "genlock", "output"),
      port("AC Power", "power", "input"),
    ],
  },

  // Control Processors
  // Crestron CP4N — Control Processor
  {
    id: "c0a80101-0038-4000-8000-000000000056",
    deviceType: "control-processor",
    label: "Crestron CP4N",
    manufacturer: "Crestron",
    modelNumber: "CP4N",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/Control-System/Rack-Mount/CP4N",
    searchTerms: ["crestron", "control", "processor", "automation", "cp4"],
    ports: [
      port("LAN", "ethernet", "bidirectional"),
      port("Control Subnet", "ethernet", "bidirectional"),
      port("COM (RS-232)", "serial", "bidirectional"),
      port("IR/Serial", "serial", "output"),
      port("Relay", "gpio", "output"),
      port("Versiport I/O", "gpio", "bidirectional"),
      port("Cresnet", "serial", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // Tally Systems
  // BMD GPI and Tally Interface
  {
    id: "c0a80101-0039-4000-8000-000000000057",
    deviceType: "tally-system",
    label: "BMD GPI & Tally",
    manufacturer: "Blackmagic Design",
    modelNumber: "GPI and Tally Interface",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemconstellation/techspecs/W-ATC-03",
    searchTerms: ["blackmagic", "tally", "gpi", "gpio", "indicator"],
    ports: [
      port("Ethernet In", "ethernet", "bidirectional"),
      port("Ethernet Loop", "ethernet", "bidirectional"),
      port("GPI In (8ch)", "gpio", "input"),
      port("GPI Out (8ch)", "gpio", "output"),
      port("AC Power", "power", "input"),
    ],
  },

  // AV-over-IP
  // Crestron DM-NVX-351 — AV-over-IP Encoder/Decoder
  {
    id: "c0a80101-003a-4000-8000-000000000058",
    deviceType: "av-over-ip",
    label: "Crestron DM-NVX-351",
    manufacturer: "Crestron",
    modelNumber: "DM-NVX-351",
    referenceUrl: "https://www.crestron.com/Products/Catalog/AV-Over-IP/DM-NVX-AV-Over-IP/Video-Endpoint/DM-NVX-351",
    searchTerms: ["crestron", "nvx", "av-over-ip", "networked av", "encoder", "decoder"],
    ports: [
      port("HDMI In 1", "hdmi", "input"),
      port("HDMI In 2", "hdmi", "input"),
      port("HDMI Out", "hdmi", "output"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("SFP", "fiber", "bidirectional", "sfp"),
      port("Analog Audio", "analog-audio", "bidirectional"),
      port("USB Host", "usb", "bidirectional"),
      port("USB Device", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // Power Distribution
  {
    id: "c0a80101-003b-4000-8000-000000000059",
    deviceType: "power-distribution",
    label: "Power Strip",
    searchTerms: ["power strip", "power bar", "outlet strip", "surge protector"],
    ports: [
      port("AC In", "power", "input"),
      port("Out 1", "power", "output"),
      port("Out 2", "power", "output"),
      port("Out 3", "power", "output"),
      port("Out 4", "power", "output"),
      port("Out 5", "power", "output"),
      port("Out 6", "power", "output"),
    ],
  },
  {
    id: "c0a80101-003c-4000-8000-000000000060",
    deviceType: "power-distribution",
    label: "Rack PDU",
    searchTerms: ["pdu", "power distribution", "rack power"],
    ports: [
      port("AC In", "power", "input"),
      port("Out 1", "power", "output"),
      port("Out 2", "power", "output"),
      port("Out 3", "power", "output"),
      port("Out 4", "power", "output"),
      port("Out 5", "power", "output"),
      port("Out 6", "power", "output"),
      port("Out 7", "power", "output"),
      port("Out 8", "power", "output"),
      port("Out 9", "power", "output"),
      port("Out 10", "power", "output"),
      port("Out 11", "power", "output"),
      port("Out 12", "power", "output"),
    ],
  },
];
